In [1]:
import pandas as pd
import os
from collections import defaultdict
from pprint import pprint
import re

In [2]:
data_dir = "./data"
raw_dir = os.path.join(data_dir, "raw")
processed_dir = os.path.join(data_dir, "structured")

survey_filename = "survey_1.csv"
raw_path = os.path.join(raw_dir, survey_filename)
processed_path = os.path.join(processed_dir, survey_filename)

In [3]:
df = pd.read_csv(raw_path)

df["Orientación sexual"] = (
    df["Orientación Sexual"]
    .fillna(df["Orientación Sexual.1"])
)

meta_cols = {
    "Marca temporal": "timestamp",
    "Edad": "age",
    "Género": "gender",
    "Orientación sexual": "sexual_orientation",
}

drop_cols = [
    "Marca temporal",
    "Edad",
    "Género",
    "Orientación Sexual",
    "Orientación Sexual.1",
    "Orientación sexual",
]

meta = (
    df[list(meta_cols.keys())]
    .rename(columns=meta_cols)
    .copy()
)

data = df.drop(columns=drop_cols)

meta.head()

             timestamp  age    gender sexual_orientation
0  18/04/2026 21:20:28   21  Femenino       Heterosexual
1  19/04/2026 15:15:37   24  Femenino         Homosexual
2  19/04/2026 15:44:41   23     Otros         Homosexual
3  19/04/2026 20:57:37   20     Otros         Homosexual
4  20/04/2026 15:15:28   23  Femenino         Homosexual

In [4]:
free_text_cols = [
	c for c in data.columns
	if "(1 frase)" in c
]

print(free_text_cols)

['Escribe tu respuesta según la opción elegida en la pregunta anterior (1 frase).', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase).', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..1', 'Escribe cómo saludarías a Pablo, tu amigo online que hiciste hace unas semanas (1 frase).', 'Escribe tu respuesta según la opción elegida en la pregunta anterior (1 frase)..1', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..2', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..3', 'Escribe cómo saludarías a Lucía, tu amiga online que hiciste hace una semanas (1 frase).']

In [5]:
blocks = []
current_block = []

for col in data.columns:
	current_block.append(col)
	
	if col in free_text_cols:
		blocks.append(current_block)
		current_block = []
		
print(blocks)

[['¿Qué tono tendría tu respuesta?', 'Escribe tu respuesta según la opción elegida en la pregunta anterior (1 frase).'], ['¿Cómo de preocupado estás por Pablo?', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase).'], ['¿Cómo te lo estás pasando?', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..1'], ['Escribe cómo saludarías a Pablo, tu amigo online que hiciste hace unas semanas (1 frase).'], ['¿Qué tono tendría tu respuesta?.1', 'Escribe tu respuesta según la opción elegida en la pregunta anterior (1 frase)..1'], ['¿Cómo de preocupado estás por Lucía?', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..2'], ['¿Cómo te lo estás pasando?.1', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..3'], ['Escribe cómo saludarías a Lucía, tu amiga online que hiciste hace una semanas (1 frase).']]

In [6]:
n = len(blocks) // 2

first_half = blocks[:n]
second_half = blocks[n:]

print(first_half)

# print(second_half)

[['¿Qué tono tendría tu respuesta?', 'Escribe tu respuesta según la opción elegida en la pregunta anterior (1 frase).'], ['¿Cómo de preocupado estás por Pablo?', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase).'], ['¿Cómo te lo estás pasando?', 'Escribe tu respuesta según la opción seleccionada en la pregunta anterior (1 frase)..1'], ['Escribe cómo saludarías a Pablo, tu amigo online que hiciste hace unas semanas (1 frase).']]

In [7]:
merged = defaultdict(list)
situations = [1, 4, 7, 10]

merged = {
    situation: [first, second]
    for situation, first, second in zip(
        situations,
        first_half,
        second_half,
    )
}

In [8]:
pprint(merged[1])

[['¿Qué tono tendría tu respuesta?',
  'Escribe tu respuesta según la opción elegida en la pregunta anterior (1 '
  'frase).'],
 ['¿Qué tono tendría tu respuesta?.1',
  'Escribe tu respuesta según la opción elegida en la pregunta anterior (1 '
  'frase)..1']]

In [9]:
rows = []

for i, survey_row in df.iterrows():
    row = {
        col: meta.loc[i, col]
        for col in meta.columns
    }

    for idx, pairs in merged.items():
        for columns in pairs:

            labels = ["text"] if len(columns) == 1 else ["choice", "text"]

            for column, label in zip(columns, labels):
                value = survey_row[column]

                if pd.notna(value):
                    row[f"situation_{idx}_{label}"] = value
                    
    rows.append(row)

clean_df = pd.DataFrame(rows)
clean_df.head()

,timestamp,age,gender,sexual_orientation,situation_1_choice,situation_1_text,situation_4_choice,situation_4_text,situation_7_choice,situation_7_text,situation_10_text
0,18/04/2026 21:20:28,21,Femenino,Heterosexual,Amigable y cordial.,"“Hola, soy Patri! Encantada de conocerte”","Preocupado, mostrando interés por cómo se encu...",“¿Enserio? ¿Pero te has tomado algo para el do...,"Bien, divirtiéndote y disfrutando del momento.","""Super bien! La verdad es que todos son bastan...","""Heyy sigues despierto? Estás haciendo algo ah..."
1,19/04/2026 15:15:37,24,Femenino,Homosexual,Amigable y cordial.,"Holaaa buenas, soy Nombre, acabo de llegar y e...","Indiferente, sin mostrar especial interés.","Ayyy qué rollo, bueno al menos ya estás bien","Más o menos, no del todo cómodo.",no aguanto más me quiero ir xd,"volví de la fiesta, sigues por ahí?"
2,19/04/2026 15:44:41,23,Otros,Homosexual,Tímido y reservado.,"Hola, Laura, encantado.","Preocupado, mostrando interés por cómo se encu...","Ay, estas bien?","Más o menos, no del todo cómodo.",No muy bien. No conozco a casi nadie y no sé q...,"Holi, ya he vuelto de la fiesta, qué tal te ha..."
3,19/04/2026 20:57:37,20,Otros,Homosexual,Tímido y reservado.,Emmm. Hola.,"Preocupado, mostrando interés por cómo se encu...",oooo Todo guay seguro?,"Bien, divirtiéndote y disfrutando del momento.",Guay la verdad q la gente es muy maja aqui,"Estoy en casa ya, que tal??"
4,20/04/2026 15:15:28,23,Femenino,Homosexual,Amigable y cordial.,Hola Laura yo soy Rocío encantada,"Preocupado, mostrando interés por cómo se encu...",Ay no pobre cómo estás ahora ?,"Bien, divirtiéndote y disfrutando del momento.",Muy bien!,Hola Lucía! Tú día qué tal ha ido ?

In [10]:
def clean_text(text):
	if pd.isna(text):
		return text

	out = str(text)

	out = re.sub(r"\(.*?\)", "", out)
	out = re.sub(r"\*.*?\*", "", out)
	out = re.sub(r"[\"“”]", "", out)
	out = re.sub(r"\s+", " ", out)
	out = out.strip()

	return out

In [11]:
text_columns = [
    column
    for column in clean_df.columns
    if "text" in column
]

clean_df[text_columns] = clean_df[text_columns].map(clean_text)

display(clean_df)

,timestamp,age,gender,sexual_orientation,situation_1_choice,situation_1_text,situation_4_choice,situation_4_text,situation_7_choice,situation_7_text,situation_10_text
0,18/04/2026 21:20:28,21,Femenino,Heterosexual,Amigable y cordial.,"Hola, soy Patri! Encantada de conocerte","Preocupado, mostrando interés por cómo se encu...",¿Enserio? ¿Pero te has tomado algo para el dol...,"Bien, divirtiéndote y disfrutando del momento.",Super bien! La verdad es que todos son bastant...,Heyy sigues despierto? Estás haciendo algo ahora?
1,19/04/2026 15:15:37,24,Femenino,Homosexual,Amigable y cordial.,"Holaaa buenas, soy Nombre, acabo de llegar y e...","Indiferente, sin mostrar especial interés.","Ayyy qué rollo, bueno al menos ya estás bien","Más o menos, no del todo cómodo.",no aguanto más me quiero ir xd,"volví de la fiesta, sigues por ahí?"
2,19/04/2026 15:44:41,23,Otros,Homosexual,Tímido y reservado.,"Hola, Laura, encantado.","Preocupado, mostrando interés por cómo se encu...","Ay, estas bien?","Más o menos, no del todo cómodo.",No muy bien. No conozco a casi nadie y no sé q...,"Holi, ya he vuelto de la fiesta, qué tal te ha..."
3,19/04/2026 20:57:37,20,Otros,Homosexual,Tímido y reservado.,Emmm. Hola.,"Preocupado, mostrando interés por cómo se encu...",oooo Todo guay seguro?,"Bien, divirtiéndote y disfrutando del momento.",Guay la verdad q la gente es muy maja aqui,"Estoy en casa ya, que tal??"
4,20/04/2026 15:15:28,23,Femenino,Homosexual,Amigable y cordial.,Hola Laura yo soy Rocío encantada,"Preocupado, mostrando interés por cómo se encu...",Ay no pobre cómo estás ahora ?,"Bien, divirtiéndote y disfrutando del momento.",Muy bien!,Hola Lucía! Tú día qué tal ha ido ?
5,21/04/2026 15:19:26,24,Femenino,Bisexual,Amigable y cordial.,"Hol, soy Briana un gusto","Indiferente, sin mostrar especial interés.","Me alegra escuchar que ya te sientes mejor, el...","Más o menos, no del todo cómodo.","Bien, ósea recién estoy conociendo a la gente ...",Hey como estas ? Sigues despierto ?
6,4/05/2026 17:19:20,23,Masculino,Heterosexual,Tímido y reservado.,Hola,"Indiferente, sin mostrar especial interés.",,"Bien, divirtiéndote y disfrutando del momento.",Bien :),Hola
7,4/05/2026 18:35:52,18,Masculino,Heterosexual,Amigable y cordial.,"Buenas, yo soy Miguel, encantado","Preocupado, mostrando interés por cómo se encu...",Y eso? Que te pasa?,"Bien, divirtiéndote y disfrutando del momento.","Bien, aquí disfrutando con los amigos, tu que ...","Holaaa, que tall?"
8,4/05/2026 18:38:38,18,Masculino,Heterosexual,Amigable y cordial.,Encantado soy ...,"Preocupado, mostrando interés por cómo se encu...",Así? No es nada grave no?,"Más o menos, no del todo cómodo.","Bueno bien, no conozco muy bien a esta gente","Ya estoy en casa, tu que tal? Que haces?"
9,4/05/2026 19:26:02,22,Masculino,Heterosexual,Amigable y cordial.,"Hola, soy Gianfranco un placer","Preocupado, mostrando interés por cómo se encu...","Espero que te mejores pronto!, por lo menos no...","Bien, divirtiéndote y disfrutando del momento.",Súper bien!,Lucía! avisame cuando llegues a tu casa
10,4/05/2026 19:39:39,18,Masculino,Otros,Amigable y cordial.,Qué tal? Soy Spamton,"Indiferente, sin mostrar especial interés.","Bueno, lo importante es que ya estás bien :P","Bien, divirtiéndote y disfrutando del momento.","Bien, 'ta guay el cumple",Qué tal todo? :>
11,4/05/2026 20:04:44,22,Masculino,Bisexual,Amigable y cordial.,"Hola, ¿qué tal? Yo soy Pepe.","Preocupado, mostrando interés por cómo se encu...",Jolines. Espero que mejores.,"Bien, divirtiéndote y disfrutando del momento.",Genial. Muchas gracias por invitarme.,Hola Lucía. ¿Qué tal te lo pasaste? ¿Llegaste ...
12,4/05/2026 20:08:14,22,Masculino,Bisexual,Amigable y cordial.,Hola. Soy Pepe. Encantado.,"Preocupado, mostrando interés por cómo se encu...",Espero que te mejores pronto. Si necesitas ayu...,"Bien, divirtiéndote y disfrutando del momento.",¡Está siendo increíble! Muchas gracias por con...,"Hola, Lucía. Soy Pepe. ¿Qué tal te lo pasaste?"
13,4/05/2026 20:16:23,21,Masculino,Heterosexual,Amigable y cordial.,"Baseado en mi personalidad, si una persuna fue...","Indiferente, sin mostrar especial interés.","Indiferente, pues aún no conosco esa persona.","Bien, divirtiéndote y disfrutando del momento.","Yo estaría disfruanto del momento, y empezaría...","Buenas noches, Lucía, que tal? he regresado a ..."
14,4/05/2026 21:33:31,25,Masculino,Heterosexual,Amigable y cordial.,"Hola! Soy , encantado también","Preocupado, mostrando interés por cómo se encu...","Ahh, me alegra que estés mejor","Bien, divirtiéndote y disfrutando del momento.","Bien, ya abrieron los regalos y justo ahorita ...","Heyyy, qué tal? Justo volví a casa"
15,5/05/2026 7:41:44,18,Masculino,Heterosexual,Amigable y cordial.,"Buenas, soy Jorge. Encantado.","Preocupado, mostrando interés por cómo se encu...","Aibaa, ¿ya estás mejor entonces??","Más o menos, no del todo cómodo.","Bueno, ahí vamos jajaja","Eyyy, ya estoy en casa. ¿Tú que tal??"
16,5/05/2026 10:09:05,18,Masculino,Heterosexual,Amigable y cordial.,"Qué tal, soy Miguel","Preocupado, mostrando interés por cómo se encu...","Que mal, segura que te encuentras bien?","Bien, divirtiéndote y disfrutando del momento.","Pues muy bien, luego tengo que contarte detall...","Oal, te apetece llamada luego y te cuento lo d..."
17,5/05/2026 12:56:25,20,Femenino,Bisexual,Amigable y cordial.,¡Hola! Yo me llamo X,"Preocupado, mostrando interés por cómo se encu...","Anda, ¿y eso, has estado enfermo?","Bien, divirtiéndote y disfrutando del momento.","Bien! Estoy conociendo a gente guay, creo que ...","Ey, ya he vuelto a casa, te hace charlar?"
18,7/05/2026 16:06:45,23,Femenino,Heterosexual,Amigable y cordial.,"Holaaa, soy mi nombre que ta","Preocupado, mostrando interés por cómo se encu...","Oh, bueno tampoco te perdiste mucho. A ver si ...","Bien, divirtiéndote y disfrutando del momento.",Muy bien la gente súper maja. Estoy conociendo...,Heeey estás despierto?
19,7/05/2026 16:13:54,23,Masculino,Heterosexual,Tímido y reservado.,Hola,"Preocupado, mostrando interés por cómo se encu...",Ay y eso?,"Bien, divirtiéndote y disfrutando del momento.",Bien,Hola! Qué tal?
20,7/05/2026 19:37:37,23,Masculino,Heterosexual,Amigable y cordial.,"Hola Laura, ¿qué tal? Soy , encantado","Preocupado, mostrando interés por cómo se encu...","¿Y eso, te has puesto mala o ha sido de sopetón?","Bien, divirtiéndote y disfrutando del momento.","De puta madre, la verdad que la Paula se lo ha...","Eyyyyyy, de vuelta en home ¿andas despierta?"
21,7/05/2026 21:30:44,65,Femenino,Heterosexual,Amigable y cordial.,"Hola, yo María, lo mismo digo.","Indiferente, sin mostrar especial interés.",Ahh! Qué has estado haciendo?,"Bien, divirtiéndote y disfrutando del momento.","Genial, son muy guay, me siento como si los co...","Hola, sigues ahí. Qué estás haciendo?"
22,8/05/2026 20:20:30,57,Femenino,Heterosexual,Amigable y cordial.,Educada,"Indiferente, sin mostrar especial interés.",No lo conozco mucho,"Más o menos, no del todo cómodo.",No conozco a casi nadie,Como estás?
23,11/05/2026 23:09:56,23,Otros,Homosexual,Amigable y cordial.,Hola Laura! Encantado de conocerte yo soy me l...,"Preocupado, mostrando interés por cómo se encu...",Ha tenido que ser grave para que no vayas a cl...,"Bien, divirtiéndote y disfrutando del momento.",Me lo estoy pasando super y estoy hablando con...,Heyyy acabo de volver de la fiesta tú que has ...
24,11/05/2026 23:30:19,25,Masculino,Homosexual,Neutral.,Hola yo soy Jaime,"Indiferente, sin mostrar especial interés.",Que raro bueno ya estas bien xddd,"Bien, divirtiéndote y disfrutando del momento.",no respondería porque me lo estoy pasando bien,Holaaaa que haces ya me fui :v
25,13/05/2026 20:25:49,19,Masculino,Heterosexual,Amigable y cordial.,Hola! Soy He,"Indiferente, sin mostrar especial interés.",Vale....,"Bien, divirtiéndote y disfrutando del momento.","Bien, intentando conocer a todo el mundo y tal",Ya llegue a mi casa. Ha estado bien la fiesta ...
26,14/05/2026 17:36:00,23,Masculino,Heterosexual,Amigable y cordial.,"Encantado, soy Jianuo. ¿Tú también eres nueva ...","Preocupado, mostrando interés por cómo se encu...",¿Segura que estás ya bien? Intenta descansar b...,"Más o menos, no del todo cómodo.","La gente es maja, pero hay demasiada peña.",YOOOOOOOO YA HE VUELTO A CASA :DDDDDDD
27,14/05/2026 20:39:51,18,Femenino,Homosexual,Tímido y reservado.,"Hola, soy ; mucho gusto.","Preocupado, mostrando interés por cómo se encu...","Ay pobre, dormiste mal o algo?","Más o menos, no del todo cómodo.","Aún me cuesta acercarme un poco a la gente, pe...",holiiii q tal

In [12]:
clean_df.to_csv(processed_path, index=False)

situations_dir = os.path.join(processed_dir, "situations")
os.makedirs(situations_dir, exist_ok=True)

for s in situations:
    cols = [
        col for col in clean_df.columns
        if col.startswith(f"situation_{s}_")
    ]

    subdf = clean_df[
        ["timestamp", "age", "gender", "sexual_orientation", *cols]
    ].copy()

    subdf = subdf.rename(columns={
        f"situation_{s}_choice": "choice",
        f"situation_{s}_text": "text"
    })

    path = os.path.join(situations_dir, f"situation_{s}.csv")
    subdf.to_csv(path, index=False)