In [1]:
import sys
sys.path.append('..')

from collections import defaultdict
from adaptation.misc import NameAnonymizer
from datetime import datetime
import pandas as pd
import json
import os

In [2]:
data_dir = "./data"
raw_dir = os.path.join(data_dir, "raw")
pretest_dir = os.path.join(raw_dir, "pretest")
postest_dir = os.path.join(raw_dir, "postest")
gameplay_raw_path = os.path.join(raw_dir, "gameplay", "full_xapi_data_33.ndjson")

processed_dir = os.path.join(data_dir, "processed")
pretest_path = os.path.join(processed_dir, "pretest.csv")
postest_path = os.path.join(processed_dir, "postest.csv")
gameplay_path = os.path.join(processed_dir, "gameplay.ndjson")

adaptation_dir = os.path.join("../adaptation", "data")
metadata_path = os.path.join(adaptation_dir, "metadata.json")
situation_dir = os.path.join(adaptation_dir, "processed")
whitelist_path = os.path.join(adaptation_dir, "name_whitelist.txt")
names_path = os.path.join(adaptation_dir, "nombres-propios-es.txt")

In [3]:
with open(metadata_path, "r", encoding="utf-8") as f:
	config = json.load(f)

node_order = []
node_context = {}

for key in sorted(config.keys(), key=int):
	item = config[key]

	scene = os.path.splitext(os.path.basename(item["file"]))[0]
	scene = scene[0].upper() + scene[1:]

	part = item["object"].split(".")[0]

	node = f"{scene}.{part}"

	node_order.append(node)

print(node_order)

['Scene1Classroom.part2', 'Scene1Bedroom1.computer1', 'Scene1Bedroom1.computer2', 'Scene1Bedroom2.computer', 'Scene2Break.part2', 'Scene3Bedroom.main', 'Scene4Backyard.mainConversation', 'Scene4Garage.phone1', 'Scene4Garage.photo', 'Scene4Bedroom.phone', 'Scene6BedroomRouteA1.phone', 'Scene6LunchRouteB.phone']

In [4]:
pretest_df = pd.read_csv(pretest_path, encoding="utf-8")
postest_df = pd.read_csv(postest_path, encoding="utf-8")

In [5]:
def extract_likert(value: str):
	return int(value.split(" - ")[0])

In [6]:
def load_json_files(dir: str) -> list[dict]:
	data = []

	for filename in os.listdir(dir):
		if filename.endswith(".json"):
			filepath = os.path.join(dir, filename)

			with open(filepath, "r", encoding="utf-8") as f:
				data.append(json.load(f))

	return data

In [7]:
pretests = load_json_files(pretest_dir)

In [8]:
rows = []

for pretest in pretests:
	# Las cuatro últimas respuestas corresponden a las preguntas likert
	values = list(pretest.values())
	likert_values = values[-4:]

	row = {
		"access_code": pretest["Código de acceso"],
		"age": int(pretest["Edad"]),
		"gender": pretest["Género"] or pretest["Género [Otro]"],
		"education_level": pretest["Nivel de estudios actual"],
		"study_area": pretest["Área principal de estudios"] or pretest["Área principal de estudios [Otro]"],
		"dialogue_advance_only": extract_likert(likert_values[0]),
		"dialogue_predefined_options": extract_likert(likert_values[1]),
		"dialogue_free_text": extract_likert(likert_values[2]),
		"dialogue_hybrid": extract_likert(likert_values[3]),
	}

	rows.append(row)

df = pd.DataFrame(rows)

In [9]:
print(df.dtypes)

access_code                      str
age                            int64
gender                           str
education_level                  str
study_area                       str
dialogue_advance_only          int64
dialogue_predefined_options    int64
dialogue_free_text             int64
dialogue_hybrid                int64
dtype: object

In [10]:
display(df)

,access_code,age,gender,education_level,study_area,dialogue_advance_only,dialogue_predefined_options,dialogue_free_text,dialogue_hybrid
0,22_eych,24,Otro,Estudios universitarios,Informática,1,4,4,4
1,22_flzl,22,Masculino,Estudios universitarios,Informática,2,4,2,4
2,22_gmvf,22,Masculino,Estudios universitarios,Ciencias de la Salud,2,4,3,4
3,22_krpb,22,Masculino,Estudios universitarios,"Ciencias Formales (ej. Matemáticas, Estadístic...",4,4,2,3
4,22_mkps,21,Femenino,Estudios universitarios,Educación,3,4,4,5
5,22_swol,23,Femenino,Estudios universitarios,Educación,1,4,3,4
6,22_tstp,22,Femenino,Estudios universitarios,Ciencias de la Salud,2,4,5,4
7,22_tsvn,24,Femenino,Estudios universitarios,Informática,1,5,2,4
8,22_vezs,24,Femenino,Estudios universitarios,Ciencias Sociales,3,3,3,3
9,22_wuak,65,Femenino,Estudios universitarios,Educación,5,1,1,1

In [11]:
df.to_csv(pretest_path, index=False, encoding="utf-8")

In [12]:
postests = load_json_files(postest_dir)

In [13]:
rows = []

for postest in postests:
	values = list(postest.values())
	
	# Saltarse metadata
	# response_id, submission_date, last_page, language, seed,
	# access_code, start_date, last_action_date
	likert_values = values[8:-2]

	# Dividir en secciones
	sus = likert_values[:10]
	free_text = likert_values[10:13]
	hybrid = likert_values[13:17]
	preferences = likert_values[17:21]

	row = {
		"access_code": postest["Código de acceso"],

		# SUS
		"sus_use_frequently": extract_likert(sus[0]),
		"sus_unnecessarily_complex": extract_likert(sus[1]),
		"sus_easy_to_use": extract_likert(sus[2]),
		"sus_need_technical_support": extract_likert(sus[3]),
		"sus_well_integrated": extract_likert(sus[4]),
		"sus_too_much_inconsistency": extract_likert(sus[5]),
		"sus_easy_to_learn": extract_likert(sus[6]),
		"sus_cumbersome": extract_likert(sus[7]),
		"sus_confident": extract_likert(sus[8]),
		"sus_need_to_learn": extract_likert(sus[9]),

		# Texto libre
		"free_text_easy_to_express": extract_likert(free_text[0]),
		"free_text_understood": extract_likert(free_text[1]),
		"free_text_coherent_responses": extract_likert(free_text[2]),

		# Diálogos híbridos
		"hybrid_more_natural": extract_likert(hybrid[0]),
		"hybrid_more_freedom": extract_likert(hybrid[1]),
		"hybrid_improves_interaction": extract_likert(hybrid[2]),
		"hybrid_overall_satisfaction": extract_likert(hybrid[3]),

		# Preferencia de diálogos
		"dialogue_advance_only": extract_likert(preferences[0]),
		"dialogue_predefined_options": extract_likert(preferences[1]),
		"dialogue_free_text": extract_likert(preferences[2]),
		"dialogue_hybrid": extract_likert(preferences[3]),

		# Preguntas abiertas
		"liked_most": values[-2],
		"comments": values[-1],
	}

	rows.append(row)

df = pd.DataFrame(rows)

In [14]:
print(df.dtypes)

access_code                       str
sus_use_frequently              int64
sus_unnecessarily_complex       int64
sus_easy_to_use                 int64
sus_need_technical_support      int64
sus_well_integrated             int64
sus_too_much_inconsistency      int64
sus_easy_to_learn               int64
sus_cumbersome                  int64
sus_confident                   int64
sus_need_to_learn               int64
free_text_easy_to_express       int64
free_text_understood            int64
free_text_coherent_responses    int64
hybrid_more_natural             int64
hybrid_more_freedom             int64
hybrid_improves_interaction     int64
hybrid_overall_satisfaction     int64
dialogue_advance_only           int64
dialogue_predefined_options     int64
dialogue_free_text              int64
dialogue_hybrid                 int64
liked_most                        str
comments                          str
dtype: object

In [15]:
display(df)

,access_code,sus_use_frequently,sus_unnecessarily_complex,sus_easy_to_use,sus_need_technical_support,sus_well_integrated,sus_too_much_inconsistency,sus_easy_to_learn,sus_cumbersome,sus_confident,...,hybrid_more_natural,hybrid_more_freedom,hybrid_improves_interaction,hybrid_overall_satisfaction,dialogue_advance_only,dialogue_predefined_options,dialogue_free_text,dialogue_hybrid,liked_most,comments
0,22_eych,4,2,4,1,4,5,5,1,2,...,4,5,5,4,1,4,4,4,Que se pueda escribir de forma interactiva y s...,Especificar un número limite de caracteres qui...
1,22_flzl,1,1,2,2,5,5,2,4,2,...,1,1,1,2,2,4,1,1,,El mayor problema que veo con el sistema de re...
2,22_gmvf,3,1,4,2,4,1,4,1,5,...,4,1,4,4,4,4,2,3,La habilidad de la IA generativa para desarrol...,"Deberían ser más permisivas las respuestas, ya..."
3,22_krpb,3,2,4,1,3,3,4,2,4,...,3,4,4,4,4,4,2,4,me ha gustado en que en algunas ocasiones así ...,como he dicho antes a veces le podía costa cap...
4,22_mkps,5,2,5,2,4,1,3,2,4,...,5,3,5,4,4,4,3,4,me ha gustado en el que verdaderamente son un ...,al final esta muy bien el tema de que tú tenga...
5,22_swol,3,2,4,1,4,1,4,1,4,...,4,4,4,4,1,4,3,4,me gustó cómo el sistema usaba lo que yo escri...,
6,22_tstp,4,5,4,3,3,1,4,5,4,...,4,3,4,5,2,4,4,5,,Algunas partes exigia que respondieses una cos...
7,22_tsvn,2,1,4,1,3,2,5,1,5,...,2,4,2,4,1,5,2,4,me interesaba escribir mis propias respuestas ...,El problema que veo es que normalmente los jue...
8,22_vezs,5,1,3,1,4,1,4,1,3,...,3,4,4,4,3,3,3,3,que sea automatizado,siento que esta bien equilibrado
9,22_wuak,4,3,4,2,4,2,5,2,4,...,4,4,5,5,5,4,3,3,,

In [16]:
df.to_csv(postest_path, index=False, encoding="utf-8")

In [17]:
with open(gameplay_raw_path, "r", encoding="utf-8") as f:
	records = [json.loads(line) for line in f]

print(f"Original records: {len(records)}")

Original records: 10456

In [18]:
# Mostrar todos los usuarios presentes en las trazas
users = sorted({
	record["actor"]["account"]["name"]
	for record in records
})

print(f"Usuarios encontrados ({len(users)}):")
for user in users:
	print(f" - {user}")

Usuarios encontrados (13):
 - aqog
 - cbnq
 - eych
 - flzl
 - gmvf
 - kfux
 - krpb
 - mkps
 - swol
 - tstp
 - tsvn
 - vezs
 - wuak

In [19]:
# USUARIOS A ELIMINAR
users_to_remove = {"kfux", "aqog", "cbnq", "gmvf", "muic", "jwii", "daqe"}

records = [
	record for record in records
	if record["actor"]["account"]["name"] not in users_to_remove
]

print(f"Filtered records: {len(records)}")

Filtered records: 8081

In [20]:
# Mostrar todos los usuarios presentes en las trazas
users = sorted({
	record["actor"]["account"]["name"]
	for record in records
})

print(f"Usuarios encontrados ({len(users)}):")
for user in users:
	print(f" - {user}")

Usuarios encontrados (9):
 - eych
 - flzl
 - krpb
 - mkps
 - swol
 - tstp
 - tsvn
 - vezs
 - wuak

In [21]:
THOUGHTBOX_EVENT_IDS = {
	"https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxStart",
	"https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxEnd",
}

DIALOG_TREE_PREFIX = "https://w3id.org/xapi/seriousgames/activity-types/dialog-tree/"

MATCHING_TEXT_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/MatchingText"
METHOD_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Method"
TIMESTAMP_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Timestamp"

LSTM_USERS = {"vezs", "tstp"}
# LSTM_USERS = {}

filtered_records = []

for record in records:
	object_id = record.get("object", {}).get("id", "")
	extensions = record.get("result", {}).get("extensions", {})

	if object_id in THOUGHTBOX_EVENT_IDS and TIMESTAMP_EXTENSION in extensions:
		filtered_records.append(record)
		continue

	if object_id.startswith(DIALOG_TREE_PREFIX):

		if MATCHING_TEXT_EXTENSION in extensions:
			user = record.get("actor", {}).get("account", {}).get("name")

			if user in LSTM_USERS:
				extensions[METHOD_EXTENSION] = "lstm"
			
			filtered_records.append(record)

records = filtered_records

print(f"Records after event filtering: {len(records)}")

Records after event filtering: 329

In [22]:
records.sort(key=lambda record: record["timestamp"])

print(f"Records after event filtering: {len(records)}")

Records after event filtering: 329

In [23]:
print(node_order)

['Scene1Classroom.part2', 'Scene1Bedroom1.computer1', 'Scene1Bedroom1.computer2', 'Scene1Bedroom2.computer', 'Scene2Break.part2', 'Scene3Bedroom.main', 'Scene4Backyard.mainConversation', 'Scene4Garage.phone1', 'Scene4Garage.photo', 'Scene4Bedroom.phone', 'Scene6BedroomRouteA1.phone', 'Scene6LunchRouteB.phone']

In [24]:
situation_files = []

for file in os.listdir(situation_dir):
	if file.startswith("situation_") and file.endswith(".csv"):
		situation_files.append(file)

situation_files.sort(
	key=lambda file: int(file.replace("situation_", "").replace(".csv", ""))
)

situation_dfs = {}

for file in situation_files:
	situation_number = int(file.replace("situation_", "").replace(".csv", ""))
	situation_dfs[situation_number] = pd.read_csv(os.path.join(situation_dir, file))

print(len(situation_dfs))

12

In [25]:
name_anonymizer = NameAnonymizer(
	names_path=names_path,
	whitelist_path=whitelist_path,
	replacement="{{name}}"
)

In [26]:
BRANCH_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Branch"

for record in records:
	object_id = record.get("object", {}).get("id", "")

	if object_id.startswith(DIALOG_TREE_PREFIX):
		extensions = record.get("result", {}).get("extensions", {})

		# Solo procesar si el nodo no tiene Branch
		if BRANCH_EXTENSION not in extensions:
			# Quitar el prefijo del dialog tree
			node_name = object_id[len(DIALOG_TREE_PREFIX):]

			matching_text = extensions.get(MATCHING_TEXT_EXTENSION)

			# Quedarse con las dos primeras partes separadas por "."
			node_prefix = ".".join(node_name.split(".")[:2])
			node_prefix_parts = node_prefix.split(".")

			situation_number = None
			fallback_situation = None

			# print(node_order)
			for i, expected in enumerate(node_order, start=1):
				if expected == node_prefix:
					situation_number = i
					break

				expected_parts = expected.split(".")

				if fallback_situation is None:
					expected_parts = expected.split(".")
					if expected_parts[1] == node_prefix_parts[1]:
						fallback_situation = i

			if situation_number is None:
				situation_number = fallback_situation

			situation_df = situation_dfs[situation_number]

			matching_text_clean = name_anonymizer.anonymize_names(matching_text)
			match = situation_df[situation_df["text_clean"] == matching_text_clean]

			if not match.empty:
				choice = match.iloc[0]["choice"]
			else:
				raise ValueError(f"No se encontró ninguna choice para '{matching_text_clean}' (situación {situation_number}, nodo {node_prefix})")

			extensions[BRANCH_EXTENSION] = choice

			print(node_prefix, situation_number, matching_text, choice)

Scene1Classroom.part2 1 Holaaa buenas, soy cris, acabo de llegar y estoy todavía un poco perdido, y tú? friendly
Scene1Classroom.part2 1 Hola shy
Computer.computer1 2 Hey, si soy cris, me gusta mucho jajajja msg4
Computer.computer2 3 Puff desde hace mucho tiempo 2yearsResponse
Computer.computer 4 Ay pobre, dormiste mal o algo? ask2
Computer.computer 4 Ay pobre, dormiste mal o algo? ask2
Computer.computer 4 Ahh, me alegra que estés mejor ask2
Scene2Break.part2 5 Acepto aunque no sé si podré unsure
Scene3Bedroom.main 6 Bastante, no sé le da mal jajaja. Y a ti?? liked2
Scene3Bedroom.main 6 Bro siempre pienso que no puede superarse y siempre hace algo mejor liked2
Scene3Bedroom.main 6 Me ha encantado ha sido bastante divertido liked2
Scene4Backyard.mainConversation 7 Bien :) good2
Scene4Garage.phone1 8 Le han encantado!! Le han regalado ... msg2
Scene4Garage.photo 9 No truth2
Scene4Garage.photo 9 No truth2
Scene4Bedroom.phone 10 Ya acabo la fiesta, que tal tu noche? msg3
Scene4Bedroom.phone 10 Hola msg3
Scene6LunchRouteB.phone 12 Hola Lucía, qué tal estás? No quiero que estés enfadada, y me preocupa la discusión del otro día... Podemos hablarlo? msg2
Scene6LunchRouteB.phone 12 Oyeee, tas enfadao? :( msg2
Scene6LunchRouteB.phone 12 Hola, Pablo, ¿sigues enfadada conmigo? msg2
Scene1Classroom.part2 1 ¡Hola! Yo me llamo ja friendly
Computer.computer1 2 Holaa, pues bien msg4
Computer.computer2 3 Ni me acuerdo, la tira de años 2yearsResponse
Computer.computer 4 Espero que te mejores pronto. Si necesitas ayuda con la tarea, me dices. ask2
Computer.computer 4 Que raro bueno ya estas bien xddd noAsk2
Computer.computer 4 Ha tenido que ser grave para que no vayas a clase, me alegra que ya estés mejor ya contarás que tal sigues! Y si necesitas cualquier cosa aqui estamos ask2
Scene2Break.part2 5 Acepto aunque no sé si podré unsure
Scene3Bedroom.main 6 Bro siempre pienso que no puede superarse y siempre hace algo mejor liked2
Scene3Bedroom.main 6 guapisimo liked2
Scene4Backyard.mainConversation 7 Muy bien! good2
Scene4Garage.phone1 8 Sii msg2
Scene4Garage.photo 9 No truth2
Scene4Bedroom.phone 10 Holaaa, que tall? msg3
Scene4Bedroom.phone 10 Hola msg3
Scene6BedroomRouteA1.phone 11 El que ? msg3

In [27]:
NODE_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Node"

for record in records:
	event = record.get("object", {}).get("id", "")

	if event in THOUGHTBOX_EVENT_IDS:
		extensions = record.get("result", {}).get("extensions", {})

		user = record.get("actor", {}).get("account", {}).get("name", "unknown")
		timestamp = record.get("timestamp", "unknown")
		node = extensions.get(NODE_EXTENSION, "unknown")

		event_name = event.split("/")[-1]

		print(f"{timestamp} | {user} | {event_name} | {node}")

2026-07-29T03:19:59.235Z | swol | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-29T03:19:59.239Z | swol | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-29T03:22:17.654Z | swol | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-29T03:22:17.658Z | swol | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-29T03:22:17.727Z | swol | ThoughtBoxStart | Computer.computer2.root
2026-07-29T03:22:17.730Z | swol | ThoughtBoxEnd | Computer.computer2.root
2026-07-29T03:22:17.738Z | swol | ThoughtBoxStart | Computer.computer2.root
2026-07-29T03:22:17.742Z | swol | ThoughtBoxEnd | Computer.computer2.root
2026-07-29T03:23:59.997Z | swol | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-29T03:24:00.001Z | swol | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-29T03:25:55.532Z | swol | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-29T03:25:55.536Z | swol | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-29T03:27:35.219Z | swol | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-29T03:27:35.221Z | swol | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-29T03:29:34.562Z | swol | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-29T03:29:34.564Z | swol | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-29T03:29:34.567Z | swol | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-29T03:29:34.568Z | swol | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-29T03:29:34.594Z | swol | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-29T03:29:34.595Z | swol | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-29T03:29:34.602Z | swol | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-29T03:29:34.603Z | swol | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-29T03:31:19.809Z | swol | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-29T03:31:19.811Z | swol | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-29T03:35:11.897Z | swol | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-07-29T03:35:11.899Z | swol | ThoughtBoxEnd | Scene6LunchRouteB.phone.root
2026-07-29T16:00:01.786Z | tsvn | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-29T16:00:01.807Z | tsvn | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-29T16:06:01.766Z | tsvn | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-29T16:06:01.769Z | tsvn | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-29T16:09:01.960Z | tsvn | ThoughtBoxStart | Computer.computer2.root
2026-07-29T16:09:01.961Z | tsvn | ThoughtBoxEnd | Computer.computer2.root
2026-07-29T16:15:02.483Z | tsvn | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-29T16:15:02.485Z | tsvn | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-29T16:19:16.317Z | tsvn | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-29T16:19:16.319Z | tsvn | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-29T16:23:08.515Z | tsvn | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-29T16:23:08.516Z | tsvn | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-29T16:23:08.519Z | tsvn | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-29T16:23:08.521Z | tsvn | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-29T16:23:08.523Z | tsvn | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-29T16:23:08.525Z | tsvn | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-29T16:26:48.722Z | tsvn | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-29T16:26:48.724Z | tsvn | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-29T16:29:48.318Z | tsvn | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-29T16:29:48.320Z | tsvn | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-29T16:29:48.329Z | tsvn | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-29T16:29:48.332Z | tsvn | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-29T16:29:48.393Z | tsvn | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-29T16:29:48.395Z | tsvn | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-29T16:29:48.399Z | tsvn | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-29T16:31:25.105Z | tsvn | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-29T16:31:25.109Z | tsvn | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-29T16:31:25.112Z | tsvn | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-29T16:44:36.032Z | tsvn | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-29T16:44:36.034Z | tsvn | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-31T19:57:39.197Z | mkps | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-31T19:57:39.200Z | mkps | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-31T19:57:39.205Z | mkps | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-31T19:57:39.208Z | mkps | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-31T20:00:38.975Z | mkps | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-31T20:00:38.977Z | mkps | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-31T20:00:38.980Z | mkps | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-31T20:00:38.981Z | mkps | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-31T20:03:39.134Z | mkps | ThoughtBoxStart | Computer.computer2.root
2026-07-31T20:03:39.136Z | mkps | ThoughtBoxEnd | Computer.computer2.root
2026-07-31T20:06:38.937Z | mkps | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-31T20:06:38.938Z | mkps | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-31T20:10:14.338Z | mkps | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-31T20:10:14.341Z | mkps | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-31T20:10:14.390Z | mkps | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-31T20:10:14.393Z | mkps | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-31T20:13:14.117Z | mkps | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-31T20:13:14.119Z | mkps | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-31T20:13:14.123Z | mkps | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-31T20:13:14.125Z | mkps | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-31T20:16:16.046Z | mkps | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-31T20:16:16.048Z | mkps | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-31T20:19:15.706Z | mkps | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-31T20:19:15.709Z | mkps | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-31T20:19:15.711Z | mkps | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-31T20:19:15.713Z | mkps | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-31T20:19:15.721Z | mkps | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-31T20:19:15.723Z | mkps | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-31T20:21:40.430Z | mkps | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-31T20:21:40.432Z | mkps | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-31T20:21:40.436Z | mkps | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-31T20:21:40.437Z | mkps | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-31T20:27:42.286Z | mkps | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-07-31T20:27:42.288Z | mkps | ThoughtBoxEnd | Scene6LunchRouteB.phone.root
2026-08-02T17:05:10.785Z | eych | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-08-02T17:05:10.789Z | eych | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-08-02T17:08:10.973Z | eych | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-08-02T17:08:10.975Z | eych | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-08-02T17:11:10.887Z | eych | ThoughtBoxStart | Computer.computer2.root
2026-08-02T17:11:10.888Z | eych | ThoughtBoxEnd | Computer.computer2.root
2026-08-02T17:13:08.100Z | eych | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-08-02T17:13:08.102Z | eych | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-08-02T17:16:07.820Z | eych | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-08-02T17:16:07.822Z | eych | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-08-02T17:16:07.825Z | eych | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-08-02T17:16:07.827Z | eych | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-08-02T17:19:18.307Z | eych | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-02T17:19:18.309Z | eych | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-02T17:19:18.311Z | eych | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-02T17:19:18.313Z | eych | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-02T17:22:18.064Z | eych | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-08-02T17:22:18.065Z | eych | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-08-02T17:22:18.092Z | eych | ThoughtBoxStart | Scene4Garage.phone1.root
2026-08-02T17:25:18.297Z | eych | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-08-02T17:25:18.311Z | eych | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-08-02T17:25:18.314Z | eych | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-08-02T17:25:18.394Z | eych | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-08-02T17:27:50.841Z | eych | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-08-02T17:34:03.799Z | eych | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-08-02T17:34:03.800Z | eych | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-08-02T18:31:54.283Z | flzl | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-08-02T18:31:54.286Z | flzl | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-08-02T18:34:54.500Z | flzl | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-08-02T18:34:54.502Z | flzl | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-08-02T18:37:54.273Z | flzl | ThoughtBoxStart | Computer.computer2.root
2026-08-02T18:37:54.277Z | flzl | ThoughtBoxEnd | Computer.computer2.root
2026-08-02T18:40:38.467Z | flzl | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-08-02T18:40:38.469Z | flzl | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-08-02T18:40:38.473Z | flzl | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-08-02T18:40:38.475Z | flzl | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-08-02T18:40:38.479Z | flzl | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-08-02T18:40:38.481Z | flzl | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-08-02T18:43:15.794Z | flzl | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-08-02T18:43:15.796Z | flzl | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-08-02T18:46:39.251Z | flzl | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-02T18:46:39.253Z | flzl | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-02T18:46:39.257Z | flzl | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-02T18:46:39.260Z | flzl | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-02T18:46:39.263Z | flzl | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-02T18:46:39.268Z | flzl | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-02T18:49:52.139Z | flzl | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-08-02T18:49:52.141Z | flzl | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-08-02T18:49:52.180Z | flzl | ThoughtBoxStart | Scene4Garage.phone1.root
2026-08-02T18:49:52.182Z | flzl | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-08-02T18:49:52.188Z | flzl | ThoughtBoxStart | Scene4Garage.phone1.root
2026-08-02T18:49:52.195Z | flzl | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-08-02T18:49:52.200Z | flzl | ThoughtBoxStart | Scene4Garage.phone1.root
2026-08-02T18:49:52.203Z | flzl | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-08-02T18:49:52.224Z | flzl | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-08-02T18:49:52.226Z | flzl | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-08-02T18:52:39.979Z | flzl | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-08-02T18:52:39.982Z | flzl | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-08-02T18:52:39.987Z | flzl | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-08-02T18:52:39.989Z | flzl | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-08-02T18:52:39.992Z | flzl | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-08-02T18:52:39.996Z | flzl | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-08-02T19:00:09.692Z | flzl | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-08-02T19:00:09.695Z | flzl | ThoughtBoxEnd | Scene6LunchRouteB.phone.root
2026-08-03T01:35:05.841Z | krpb | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-08-03T01:35:05.845Z | krpb | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-08-03T01:37:09.693Z | krpb | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-08-03T01:37:09.696Z | krpb | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-08-03T01:37:09.770Z | krpb | ThoughtBoxStart | Computer.computer2.root
2026-08-03T01:37:09.773Z | krpb | ThoughtBoxEnd | Computer.computer2.root
2026-08-03T01:37:54.520Z | krpb | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-08-03T01:37:54.524Z | krpb | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-08-03T01:39:47.108Z | krpb | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-08-03T01:39:47.110Z | krpb | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-08-03T01:39:47.113Z | krpb | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-08-03T01:39:47.116Z | krpb | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-08-03T01:41:48.611Z | krpb | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-03T01:41:48.614Z | krpb | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-03T01:41:48.621Z | krpb | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-08-03T01:41:48.623Z | krpb | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-08-03T01:43:36.734Z | krpb | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-08-03T01:43:36.736Z | krpb | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-08-03T01:43:36.769Z | krpb | ThoughtBoxStart | Scene4Garage.phone1.root
2026-08-03T01:43:36.772Z | krpb | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-08-03T01:43:36.785Z | krpb | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-08-03T01:43:36.787Z | krpb | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-08-03T01:45:14.353Z | krpb | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-08-03T01:45:14.357Z | krpb | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-08-03T01:48:52.813Z | krpb | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-08-03T01:48:52.815Z | krpb | ThoughtBoxEnd | Scene6LunchRouteB.phone.root

In [28]:
for record in records:
	event = record.get("object", {}).get("id", "")

	if event.startswith(DIALOG_TREE_PREFIX):
		extensions = record.get("result", {}).get("extensions", {})
		
		user = record.get("actor", {}).get("account", {}).get("name", "unknown")
		timestamp = record.get("timestamp", "unknown")
		matching_text = extensions.get(MATCHING_TEXT_EXTENSION, "unknown")

		event_name = event.split("/")[-1]

		print(f"{timestamp} | {user} | {event_name} | {matching_text}")

2026-07-23T22:29:10.883Z | vezs | Scene1Classroom.part2.thanks_similarity | Holaaa buenas, soy cris, acabo de llegar y estoy todavía un poco perdido, y tú?
2026-07-23T22:29:10.892Z | vezs | Scene1Classroom.part2.thanks_similarity | Hola
2026-07-23T22:31:47.466Z | vezs | Computer.computer1.choices_similarity | Hey, si soy cris, me gusta mucho jajajja
2026-07-23T22:31:47.508Z | vezs | Computer.computer2.root | Puff desde hace mucho tiempo
2026-07-23T22:34:54.627Z | vezs | Computer.computer.choices2_similarity | Ay pobre, dormiste mal o algo?
2026-07-23T22:34:54.631Z | vezs | Computer.computer.choices2_similarity | Ay pobre, dormiste mal o algo?
2026-07-23T22:34:54.636Z | vezs | Computer.computer.choices2_similarity | Ahh, me alegra que estés mejor
2026-07-23T22:37:15.427Z | vezs | Scene2Break.part2.choice_similarity | Acepto aunque no sé si podré
2026-07-23T22:39:34.051Z | vezs | Scene3Bedroom.main.choices_similarity | Bastante, no sé le da mal jajaja. Y a ti??
2026-07-23T22:39:34.056Z | vezs | Scene3Bedroom.main.choices_similarity | Bro siempre pienso que no puede superarse y siempre hace algo mejor
2026-07-23T22:39:34.059Z | vezs | Scene3Bedroom.main.choices_similarity | Me ha encantado ha sido bastante divertido
2026-07-23T22:41:55.834Z | vezs | Scene4Backyard.mainConversation.choices_similarity | Bien :)
2026-07-23T22:41:55.863Z | vezs | Scene4Garage.phone1.root | Le han encantado!! Le han regalado ...
2026-07-23T22:41:55.870Z | vezs | Scene4Garage.photo.choices_similarity | No
2026-07-23T22:41:55.874Z | vezs | Scene4Garage.photo.choices_similarity | No
2026-07-23T22:44:08.144Z | vezs | Scene4Bedroom.phone.root | Ya acabo la fiesta, que tal tu noche?
2026-07-23T22:44:08.150Z | vezs | Scene4Bedroom.phone.root | Hola
2026-07-23T22:49:43.663Z | vezs | Scene6LunchRouteB.phone.root | Hola Lucía, qué tal estás? No quiero que estés enfadada, y me preocupa la discusión del otro día... Podemos hablarlo?
2026-07-23T22:49:43.667Z | vezs | Scene6LunchRouteB.phone.root | Oyeee, tas enfadao? :(
2026-07-23T22:49:43.670Z | vezs | Scene6LunchRouteB.phone.root | Hola, Pablo, ¿sigues enfadada conmigo?
2026-07-24T01:58:19.409Z | tstp | Scene1Classroom.part2.thanks_similarity | ¡Hola! Yo me llamo ja
2026-07-24T02:01:19.103Z | tstp | Computer.computer1.choices_similarity | Holaa, pues bien
2026-07-24T02:04:19.430Z | tstp | Computer.computer2.root | Ni me acuerdo, la tira de años
2026-07-24T02:06:46.139Z | tstp | Computer.computer.choices2_similarity | Espero que te mejores pronto. Si necesitas ayuda con la tarea, me dices.
2026-07-24T02:06:46.143Z | tstp | Computer.computer.choices2_similarity | Que raro bueno ya estas bien xddd
2026-07-24T02:06:46.148Z | tstp | Computer.computer.choices2_similarity | Ha tenido que ser grave para que no vayas a clase, me alegra que ya estés mejor ya contarás que tal sigues! Y si necesitas cualquier cosa aqui estamos
2026-07-24T02:09:46.344Z | tstp | Scene2Break.part2.choice_similarity | Acepto aunque no sé si podré
2026-07-24T02:14:46.027Z | tstp | Scene3Bedroom.main.choices_similarity | Bro siempre pienso que no puede superarse y siempre hace algo mejor
2026-07-24T02:14:46.032Z | tstp | Scene3Bedroom.main.choices_similarity | guapisimo
2026-07-24T02:17:45.859Z | tstp | Scene4Backyard.mainConversation.choices_similarity | Muy bien!
2026-07-24T02:20:45.980Z | tstp | Scene4Garage.phone1.root | Sii
2026-07-24T02:20:45.995Z | tstp | Scene4Garage.photo.choices_similarity | No
2026-07-24T02:22:11.076Z | tstp | Scene4Bedroom.phone.root | Holaaa, que tall?
2026-07-24T02:22:11.081Z | tstp | Scene4Bedroom.phone.root | Hola
2026-07-24T02:28:14.551Z | tstp | Scene6BedroomRouteA1.phone.choices1_similarity | El que ?
2026-07-28T21:00:05.098Z | wuak | Scene1Classroom.part2.thanks_similarity | Hola
2026-07-28T21:09:04.794Z | wuak | Computer.computer1.choices_similarity | A si? Jajajs, es un grande ToniVlogs
2026-07-28T21:09:04.799Z | wuak | Computer.computer1.choices_similarity | Holaaaaa, sí me encanta ToniVlogs
2026-07-28T21:12:05.035Z | wuak | Computer.computer1.choices_similarity | ¡Hola! Siiiii, ¡me encantan sus vídeos!
2026-07-28T21:18:05.107Z | wuak | Computer.computer2.root | Desde hace 2 años.
2026-07-28T21:24:05.408Z | wuak | Computer.computer.choices2_similarity | Menos mal, espero que te recuperes pronto.
2026-07-28T21:27:04.734Z | wuak | Computer.computer.choices2_similarity | Ay no pobre cómo estás ahora ?
2026-07-28T21:27:04.741Z | wuak | Computer.computer.choices2_similarity | Ay no pobre cómo estás ahora ?
2026-07-28T21:30:28.099Z | wuak | Scene2Break.part2.choice_similarity | Pues claro, ¿dónde hay que firmar?
2026-07-28T21:30:28.101Z | wuak | Scene2Break.part2.choice_similarity | Pues claro, ¿dónde hay que firmar?
2026-07-28T21:30:28.106Z | wuak | Scene2Break.part2.choice_similarity | De acuerdo. alli estare
2026-07-28T21:37:13.189Z | wuak | Scene3Bedroom.main.choices_similarity | Me ha hecho la tarde, vaya risass
2026-07-28T21:37:13.193Z | wuak | Scene3Bedroom.main.choices_similarity | Me ha hecho la tarde, vaya risass
2026-07-28T21:37:13.197Z | wuak | Scene3Bedroom.main.choices_similarity | Me ha hecho la tarde, vaya risass
2026-07-28T21:40:12.786Z | wuak | Scene4Backyard.mainConversation.choices_similarity | Hay bastante gente que todavía no conozco pero de momento bien.
2026-07-28T21:40:12.789Z | wuak | Scene4Backyard.mainConversation.choices_similarity | Guay la verdad q la gente es muy maja aqui
2026-07-28T21:40:12.792Z | wuak | Scene4Backyard.mainConversation.choices_similarity | Guay la verdad q la gente es muy maja aqui
2026-07-28T21:43:13.095Z | wuak | Scene4Garage.phone1.root | Si, parece que si
2026-07-28T21:46:12.804Z | wuak | Scene4Garage.photo.choices_similarity | No
2026-07-28T21:46:12.848Z | wuak | Scene4Bedroom.phone.root | Como estás?
2026-07-28T21:46:12.852Z | wuak | Scene4Bedroom.phone.root | Como estás?
2026-07-28T21:46:12.855Z | wuak | Scene4Bedroom.phone.root | Como estás?
2026-07-28T21:54:07.640Z | wuak | Scene6BedroomRouteA1.phone.choices1_similarity | Vale, cuéntame
2026-07-28T21:54:07.646Z | wuak | Scene6BedroomRouteA1.phone.choices1_similarity | Sorpréndeme jajaj
2026-07-29T03:19:59.238Z | swol | Scene1Classroom.part2.thanks_similarity | Hola, soy blanca! Encantada de conocerte
2026-07-29T03:22:17.656Z | swol | Computer.computer1.choices_similarity | Hola, Lucía, yo soy blanca. Me alegra conocer a otra fan de ToniVlogs.
2026-07-29T03:22:17.728Z | swol | Computer.computer2.root | Ni me acuerdo, la tira de años
2026-07-29T03:22:17.740Z | swol | Computer.computer2.root | Desde hace mucho tiempo
2026-07-29T03:24:00.000Z | swol | Computer.computer.choices2_similarity | Ayyy, que pena. Me alegra saber que estás mejor. Necesitas algo?
2026-07-29T03:25:55.535Z | swol | Scene2Break.part2.choice_similarity | Uy no se, no conozco a nadie de ahí
2026-07-29T03:27:35.220Z | swol | Scene3Bedroom.main.choices_similarity | A mí me gustó, a ti??
2026-07-29T03:29:34.563Z | swol | Scene4Backyard.mainConversation.choices_similarity | Bien, intentando conocer a todo el mundo y tal
2026-07-29T03:29:34.567Z | swol | Scene4Backyard.mainConversation.choices_similarity | Bien
2026-07-29T03:29:34.595Z | swol | Scene4Garage.phone1.root | Sí, le han encantado
2026-07-29T03:29:34.602Z | swol | Scene4Garage.photo.choices_similarity | No la conoces, es una amiga que hice por internet
2026-07-29T03:31:19.810Z | swol | Scene4Bedroom.phone.root | Holi boli Lucía, ya volví de la fiesta, ¿quieres seguir charlando un rato o ya te vas a dormir?
2026-07-29T03:35:11.898Z | swol | Scene6LunchRouteB.phone.root | Paula, ¿sigues enfadada conmigo? Lo siento por no aceptar, pero aún no estoy lista, espero que lo entiendas.
2026-07-29T16:00:01.802Z | tsvn | Scene1Classroom.part2.thanks_similarity | ¡Hola! Yo soy Paquita, encantada
2026-07-29T16:06:01.768Z | tsvn | Computer.computer1.choices_similarity | Bien y tú? Si, me gustan sus vídeos la verdad.
2026-07-29T16:09:01.961Z | tsvn | Computer.computer2.root | ehhhh desde hace un par de años ya
2026-07-29T16:15:02.484Z | tsvn | Computer.computer.choices2_similarity | Ayyy qué rollo, bueno al menos ya estás bien
2026-07-29T16:19:16.318Z | tsvn | Scene2Break.part2.choice_similarity | Hola, muchas gracias Paula. No sé si podré ir, pero te lo agradezco mucho.
2026-07-29T16:23:08.516Z | tsvn | Scene3Bedroom.main.choices_similarity | Bro siempre pienso que no puede superarse y siempre hace algo mejor
2026-07-29T16:23:08.520Z | tsvn | Scene3Bedroom.main.choices_similarity | Siento que se aleja de lo que estoy acostumbrado a ver, no me gustaria que cambie su contenido de manera tan brusca
2026-07-29T16:23:08.524Z | tsvn | Scene3Bedroom.main.choices_similarity | No me ha gustado tanto como otros que tiene
2026-07-29T16:26:48.723Z | tsvn | Scene4Backyard.mainConversation.choices_similarity | Bien, ya abrieron los regalos y justo ahorita estamos comiendo. Qué tal tu día?
2026-07-29T16:29:48.319Z | tsvn | Scene4Garage.phone1.root | Si, le han gustado un montón. Se ha puesto muy contenta
2026-07-29T16:29:48.330Z | tsvn | Scene4Garage.photo.choices_similarity | No creo que lo conozcas va a otro insti, se llama Pablo
2026-07-29T16:29:48.394Z | tsvn | Scene4Bedroom.phone.root | Holaaaa que haces ya me fui :v
2026-07-29T16:31:25.101Z | tsvn | Scene4Bedroom.phone.root | Qué tal todo? :>
2026-07-29T16:31:25.110Z | tsvn | Scene4Bedroom.phone.root | Hola
2026-07-29T16:44:36.033Z | tsvn | Scene6BedroomRouteA1.phone.choices1_similarity | El que ?
2026-07-31T19:57:39.199Z | mkps | Scene1Classroom.part2.thanks_similarity | Hola
2026-07-31T19:57:39.206Z | mkps | Scene1Classroom.part2.thanks_similarity | Hola, soy patricia! Encantada de conocerte
2026-07-31T20:00:38.976Z | mkps | Computer.computer1.choices_similarity | En serio? Que guay. Llevo viendo a ese youtuber desde hace muchisimo tiempo.
2026-07-31T20:00:38.981Z | mkps | Computer.computer1.choices_similarity | Ey, qué tal Pablo, soy patricia. Pues le sigo desde lo de , y tú?
2026-07-31T20:03:39.135Z | mkps | Computer.computer2.root | Lo conozco desde que empezó, seguramente soy patricia sus seguidores mas viejos
2026-07-31T20:06:38.937Z | mkps | Computer.computer.choices2_similarity | Menos mal, espero que te recuperes pronto.
2026-07-31T20:10:14.340Z | mkps | Scene2Break.part2.choice_similarity | Sí, claro, voy a ir
2026-07-31T20:10:14.391Z | mkps | Scene2Break.part2.choice_similarity | Sí, claro, voy a ir
2026-07-31T20:13:14.118Z | mkps | Scene3Bedroom.main.choices_similarity | guapisimo
2026-07-31T20:13:14.124Z | mkps | Scene3Bedroom.main.choices_similarity | Me ha encantado ha sido bastante divertido
2026-07-31T20:16:16.047Z | mkps | Scene4Backyard.mainConversation.choices_similarity | Me lo estoy pasando guay
2026-07-31T20:19:15.707Z | mkps | Scene4Garage.phone1.root | Está ahora mismo abriéndolos, pero parece que sí jajaja
2026-07-31T20:19:15.712Z | mkps | Scene4Garage.phone1.root | Sí, le han encantado
2026-07-31T20:19:15.722Z | mkps | Scene4Garage.photo.choices_similarity | No creo que lo conozcas va a otro insti, se llama Pablo
2026-07-31T20:21:40.431Z | mkps | Scene4Bedroom.phone.root | Holaaaa que haces ya me fui :v
2026-07-31T20:21:40.437Z | mkps | Scene4Bedroom.phone.root | Hola
2026-07-31T20:27:42.287Z | mkps | Scene6LunchRouteB.phone.root | ¿Sigues enfadado conmigo?
2026-08-02T17:05:10.787Z | eych | Scene1Classroom.part2.thanks_similarity | Hola
2026-08-02T17:08:10.974Z | eych | Computer.computer1.choices_similarity | Hola, cual?
2026-08-02T17:11:10.888Z | eych | Computer.computer2.root | Desde hace bastante tiempo
2026-08-02T17:13:08.101Z | eych | Computer.computer.choices2_similarity | Ay, ¿qué te ha pasado?
2026-08-02T17:16:07.821Z | eych | Scene2Break.part2.choice_similarity | Uy no se, no conozco a nadie de ahí
2026-08-02T17:16:07.826Z | eych | Scene2Break.part2.choice_similarity | Que guay muchas gracias por invitarme
2026-08-02T17:19:18.308Z | eych | Scene3Bedroom.main.choices_similarity | Bastante aunque me gustó más su anterior
2026-08-02T17:19:18.312Z | eych | Scene3Bedroom.main.choices_similarity | ¡Me ha encantado, como el resto de vídeos! Es el mejor, sin duda.
2026-08-02T17:22:18.064Z | eych | Scene4Backyard.mainConversation.choices_similarity | No conozco a casi nadie
2026-08-02T17:25:18.296Z | eych | Scene4Garage.phone1.root | Si, parece que si
2026-08-02T17:25:18.313Z | eych | Scene4Garage.photo.choices_similarity | No creo que lo conozcas va a otro insti, se llama Pablo
2026-08-02T17:27:50.838Z | eych | Scene4Bedroom.phone.root | Holaaa, como va todo?
2026-08-02T17:34:03.799Z | eych | Scene6BedroomRouteA1.phone.choices1_similarity | Dime
2026-08-02T18:31:54.285Z | flzl | Scene1Classroom.part2.thanks_similarity | Hola Laura! Encantado de conocerte yo soy Pepe
2026-08-02T18:34:54.501Z | flzl | Computer.computer1.choices_similarity | Hola!! Sí, le empecé a seguir hace un tiempo y me gustan mucho sus videos. Cuál es tu favorito?
2026-08-02T18:37:54.275Z | flzl | Computer.computer2.root | Desde que tengo 12 años más o menos, siempre veía uno después de salir del cole y se convirtió en rutina
2026-08-02T18:40:38.468Z | flzl | Computer.computer.choices2_similarity | Uy que mal, que ha pasado?
2026-08-02T18:40:38.474Z | flzl | Computer.computer.choices2_similarity | Uy que mal, que ha pasado?
2026-08-02T18:40:38.480Z | flzl | Computer.computer.choices2_similarity | Que mal, segura que te encuentras bien?
2026-08-02T18:43:15.795Z | flzl | Scene2Break.part2.choice_similarity | Si, iré, muchas gracias por la invitación
2026-08-02T18:46:39.252Z | flzl | Scene3Bedroom.main.choices_similarity | Me gustó más el anterior pero ha estado divertido. A tí que te ha parecido?
2026-08-02T18:46:39.258Z | flzl | Scene3Bedroom.main.choices_similarity | Bastante aunque me gustó más su anterior
2026-08-02T18:46:39.267Z | flzl | Scene3Bedroom.main.choices_similarity | Pues ese justo no
2026-08-02T18:49:52.140Z | flzl | Scene4Backyard.mainConversation.choices_similarity | Bieeen, en una fiesta de cumpleaños. ¿Que tal tú?
2026-08-02T18:49:52.181Z | flzl | Scene4Garage.phone1.root | Está ahora mismo abriéndolos, pero parece que sí jajaja
2026-08-02T18:49:52.192Z | flzl | Scene4Garage.phone1.root | Todo bien
2026-08-02T18:49:52.202Z | flzl | Scene4Garage.phone1.root | Si mucho
2026-08-02T18:49:52.225Z | flzl | Scene4Garage.photo.choices_similarity | No, es un amigo de otro colegio
2026-08-02T18:52:39.980Z | flzl | Scene4Bedroom.phone.root | Hola, sigues ahí. Qué estás haciendo?
2026-08-02T18:52:39.988Z | flzl | Scene4Bedroom.phone.root | Hola, sigues ahí. Qué estás haciendo?
2026-08-02T18:52:39.994Z | flzl | Scene4Bedroom.phone.root | Hola
2026-08-02T19:00:09.694Z | flzl | Scene6LunchRouteB.phone.root | Hola, aún sigues enfadado por lo que ha pasado antes ?
2026-08-03T01:35:05.843Z | krpb | Scene1Classroom.part2.thanks_similarity | Hola Laura yo soy Mario encantada
2026-08-03T01:37:09.694Z | krpb | Computer.computer1.choices_similarity | Holaaaaa, sí me encanta ToniVlogs
2026-08-03T01:37:09.772Z | krpb | Computer.computer2.root | Prácticamente desde los inicios! Cuando le vi en un vídeo de otro youtuber al que sigo
2026-08-03T01:37:54.521Z | krpb | Computer.computer.choices2_similarity | Y eso? que te ocurre?
2026-08-03T01:39:47.109Z | krpb | Scene2Break.part2.choice_similarity | Vale, pero no creo que me quede mucho tiempo tengo muchos deberes
2026-08-03T01:39:47.114Z | krpb | Scene2Break.part2.choice_similarity | Uy no se, no conozco a nadie de ahí
2026-08-03T01:41:48.613Z | krpb | Scene3Bedroom.main.choices_similarity | Bro siempre pienso que no puede superarse y siempre hace algo mejor
2026-08-03T01:41:48.622Z | krpb | Scene3Bedroom.main.choices_similarity | No me ha gustado tanto como otros que tiene
2026-08-03T01:43:36.735Z | krpb | Scene4Backyard.mainConversation.choices_similarity | Bien, ósea recién estoy conociendo a la gente así que es un poco incómodo pero está chévere
2026-08-03T01:43:36.770Z | krpb | Scene4Garage.phone1.root | Si mucho
2026-08-03T01:43:36.786Z | krpb | Scene4Garage.photo.choices_similarity | eeeeeeeeeh, no, la borro si quieres
2026-08-03T01:45:14.355Z | krpb | Scene4Bedroom.phone.root | Holi boli Pablo, ya volví de la fiesta, quieres seguir charlando un rato o ya te vas a dormir?
2026-08-03T01:48:52.814Z | krpb | Scene6LunchRouteB.phone.root | Oyeee, tas enfadao? :(

In [29]:
START_EVENT = "https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxStart"
END_EVENT = "https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxEnd"

# Comienzos para cada (usuario, nodo)
pending_starts = defaultdict(list)

# Duraciones para cada (usuario, nodo)
durations = defaultdict(list)

matches = defaultdict(list)

for record in records:
	event = record.get("object", {}).get("id")

	if event in THOUGHTBOX_EVENT_IDS:
		user = record.get("actor", {}).get("account", {}).get("name")

		extensions = record.get("result", {}).get("extensions", {})
		node = extensions.get(NODE_EXTENSION)

		timestamp = datetime.fromisoformat(
			extensions.get(TIMESTAMP_EXTENSION).replace("Z", "+00:00")
		)

		key = (user, node)

		if event == START_EVENT:
			pending_starts[key].append(timestamp)

		elif event == END_EVENT:
			if pending_starts[key]:
				start = pending_starts[key].pop(0)
				duration = (timestamp - start).total_seconds()

				durations[key].append(duration)
				matches[key].append((start, timestamp, duration))

for (user, node), pairs in matches.items():
	for start, end, duration in pairs[:5]:
		print(start.isoformat(), "->", end.isoformat(), duration)

print("Average ThoughtBox duration per user/node:")
for (user, node), values in durations.items():
	avg = sum(values) / len(values)
	print(f"{user:10} | {node:40} | count={len(values)}) | avg={avg:.4f} s")

2026-07-29T03:18:34.785000+00:00 -> 2026-07-29T03:18:44.291000+00:00 9.506
2026-07-29T03:20:42.544000+00:00 -> 2026-07-29T03:21:03.455000+00:00 20.911
2026-07-29T03:21:45.991000+00:00 -> 2026-07-29T03:21:54.599000+00:00 8.608
2026-07-29T03:21:58.462000+00:00 -> 2026-07-29T03:22:05.254000+00:00 6.792
2026-07-29T03:23:27.264000+00:00 -> 2026-07-29T03:23:33.458000+00:00 6.194
2026-07-29T03:24:19.840000+00:00 -> 2026-07-29T03:24:33.956000+00:00 14.116
2026-07-29T03:26:52.422000+00:00 -> 2026-07-29T03:27:02.028000+00:00 9.606
2026-07-29T03:28:06.956000+00:00 -> 2026-07-29T03:28:14.665000+00:00 7.709
2026-07-29T03:28:17.678000+00:00 -> 2026-07-29T03:28:22.623000+00:00 4.945
2026-07-29T03:28:46.453000+00:00 -> 2026-07-29T03:29:05.160000+00:00 18.707
2026-07-29T03:29:19.760000+00:00 -> 2026-07-29T03:29:32.414000+00:00 12.654
2026-07-29T03:30:15.283000+00:00 -> 2026-07-29T03:30:34.146000+00:00 18.863
2026-07-29T03:33:47.006000+00:00 -> 2026-07-29T03:34:05.648000+00:00 18.642
2026-07-29T15:58:36.649000+00:00 -> 2026-07-29T15:59:07.025000+00:00 30.376
2026-07-29T16:04:40.153000+00:00 -> 2026-07-29T16:05:04.616000+00:00 24.463
2026-07-29T16:07:18.936000+00:00 -> 2026-07-29T16:07:30.156000+00:00 11.22
2026-07-29T16:12:52.965000+00:00 -> 2026-07-29T16:13:13.614000+00:00 20.649
2026-07-29T16:17:32.503000+00:00 -> 2026-07-29T16:17:53.746000+00:00 21.243
2026-07-29T16:22:20.419000+00:00 -> 2026-07-29T16:22:31.259000+00:00 10.84
2026-07-29T16:22:36.658000+00:00 -> 2026-07-29T16:22:53.197000+00:00 16.539
2026-07-29T16:22:57.004000+00:00 -> 2026-07-29T16:23:07.215000+00:00 10.211
2026-07-29T16:25:42.088000+00:00 -> 2026-07-29T16:25:57.143000+00:00 15.055
2026-07-29T16:26:51.720000+00:00 -> 2026-07-29T16:26:58.623000+00:00 6.903
2026-07-29T16:27:17.881000+00:00 -> 2026-07-29T16:27:33.631000+00:00 15.75
2026-07-29T16:29:26.208000+00:00 -> 2026-07-29T16:29:41.614000+00:00 15.406
2026-07-29T16:29:45.990000+00:00 -> 2026-07-29T16:29:57.765000+00:00 11.775
2026-07-29T16:30:00.647000+00:00 -> 2026-07-29T16:30:03.482000+00:00 2.835
2026-07-29T16:44:17.500000+00:00 -> 2026-07-29T16:44:23.476000+00:00 5.976
2026-07-31T19:55:11.589000+00:00 -> 2026-07-31T19:55:24.128000+00:00 12.539
2026-07-31T19:55:28.555000+00:00 -> 2026-07-31T19:55:49.466000+00:00 20.911
2026-07-31T19:59:50.350000+00:00 -> 2026-07-31T20:00:15.144000+00:00 24.794
2026-07-31T20:00:19.302000+00:00 -> 2026-07-31T20:00:35.158000+00:00 15.856
2026-07-31T20:01:49.845000+00:00 -> 2026-07-31T20:02:08.533000+00:00 18.688
2026-07-31T20:05:24.736000+00:00 -> 2026-07-31T20:05:38.473000+00:00 13.737
2026-07-31T20:08:12.118000+00:00 -> 2026-07-31T20:08:29.006000+00:00 16.888
2026-07-31T20:08:12.118000+00:00 -> 2026-07-31T20:08:29.006000+00:00 16.888
2026-07-31T20:12:09.635000+00:00 -> 2026-07-31T20:12:19.656000+00:00 10.021
2026-07-31T20:12:22.292000+00:00 -> 2026-07-31T20:12:28.374000+00:00 6.082
2026-07-31T20:15:17.372000+00:00 -> 2026-07-31T20:15:35.168000+00:00 17.796
2026-07-31T20:16:18.883000+00:00 -> 2026-07-31T20:16:24.354000+00:00 5.471
2026-07-31T20:16:29.101000+00:00 -> 2026-07-31T20:16:36.250000+00:00 7.149
2026-07-31T20:17:06.731000+00:00 -> 2026-07-31T20:17:17.984000+00:00 11.253
2026-07-31T20:20:15.476000+00:00 -> 2026-07-31T20:20:31.990000+00:00 16.514
2026-07-31T20:20:33.973000+00:00 -> 2026-07-31T20:20:41.091000+00:00 7.118
2026-07-31T20:25:57.235000+00:00 -> 2026-07-31T20:26:06.431000+00:00 9.196
2026-08-02T17:03:05.798000+00:00 -> 2026-08-02T17:03:17.236000+00:00 11.438
2026-08-02T17:06:47.317000+00:00 -> 2026-08-02T17:07:01.874000+00:00 14.557
2026-08-02T17:08:56.816000+00:00 -> 2026-08-02T17:09:09.874000+00:00 13.058
2026-08-02T17:12:18.777000+00:00 -> 2026-08-02T17:12:31.681000+00:00 12.904
2026-08-02T17:14:00.459000+00:00 -> 2026-08-02T17:14:07.564000+00:00 7.105
2026-08-02T17:14:11.249000+00:00 -> 2026-08-02T17:14:22.552000+00:00 11.303
2026-08-02T17:18:17.300000+00:00 -> 2026-08-02T17:18:30.764000+00:00 13.464
2026-08-02T17:18:35.622000+00:00 -> 2026-08-02T17:18:43.371000+00:00 7.749
2026-08-02T17:20:55.625000+00:00 -> 2026-08-02T17:21:07.148000+00:00 11.523
2026-08-02T17:22:14.831000+00:00 -> 2026-08-02T17:22:19.686000+00:00 4.855
2026-08-02T17:22:40.594000+00:00 -> 2026-08-02T17:22:51.222000+00:00 10.628
2026-08-02T17:24:59.457000+00:00 -> 2026-08-02T17:26:44.100000+00:00 104.643
2026-08-02T17:32:40.938000+00:00 -> 2026-08-02T17:32:46.462000+00:00 5.524
2026-08-02T18:29:25.826000+00:00 -> 2026-08-02T18:30:13.810000+00:00 47.984
2026-08-02T18:33:44.027000+00:00 -> 2026-08-02T18:34:44.073000+00:00 60.046
2026-08-02T18:36:20.754000+00:00 -> 2026-08-02T18:36:56.508000+00:00 35.754
2026-08-02T18:39:09.806000+00:00 -> 2026-08-02T18:39:51.617000+00:00 41.811
2026-08-02T18:39:55.778000+00:00 -> 2026-08-02T18:39:59.984000+00:00 4.206
2026-08-02T18:40:01.481000+00:00 -> 2026-08-02T18:40:13.931000+00:00 12.45
2026-08-02T18:41:35.552000+00:00 -> 2026-08-02T18:41:46.558000+00:00 11.006
2026-08-02T18:45:11.170000+00:00 -> 2026-08-02T18:45:46.206000+00:00 35.036
2026-08-02T18:45:48.397000+00:00 -> 2026-08-02T18:46:11.583000+00:00 23.186
2026-08-02T18:46:15.096000+00:00 -> 2026-08-02T18:46:19.595000+00:00 4.499
2026-08-02T18:47:41.251000+00:00 -> 2026-08-02T18:47:56.935000+00:00 15.684
2026-08-02T18:48:22.689000+00:00 -> 2026-08-02T18:48:40.996000+00:00 18.307
2026-08-02T18:48:43.934000+00:00 -> 2026-08-02T18:49:05.676000+00:00 21.742
2026-08-02T18:49:07.347000+00:00 -> 2026-08-02T18:49:13.297000+00:00 5.95
2026-08-02T18:49:33.319000+00:00 -> 2026-08-02T18:49:48.541000+00:00 15.222
2026-08-02T18:51:06.964000+00:00 -> 2026-08-02T18:51:27.501000+00:00 20.537
2026-08-02T18:51:29.642000+00:00 -> 2026-08-02T18:51:49.113000+00:00 19.471
2026-08-02T18:51:51.096000+00:00 -> 2026-08-02T18:51:54.039000+00:00 2.943
2026-08-02T18:58:53.548000+00:00 -> 2026-08-02T18:59:19.149000+00:00 25.601
2026-08-03T01:33:38.071000+00:00 -> 2026-08-03T01:33:50.108000+00:00 12.037
2026-08-03T01:35:07.175000+00:00 -> 2026-08-03T01:35:22.091000+00:00 14.916
2026-08-03T01:35:58.235000+00:00 -> 2026-08-03T01:36:20.727000+00:00 22.492
2026-08-03T01:37:21.732000+00:00 -> 2026-08-03T01:37:29.318000+00:00 7.586
2026-08-03T01:38:09.673000+00:00 -> 2026-08-03T01:38:30.517000+00:00 20.844
2026-08-03T01:38:32.763000+00:00 -> 2026-08-03T01:38:49.929000+00:00 17.166
2026-08-03T01:40:46.431000+00:00 -> 2026-08-03T01:40:54.590000+00:00 8.159
2026-08-03T01:40:56.708000+00:00 -> 2026-08-03T01:41:05.711000+00:00 9.003
2026-08-03T01:42:14.939000+00:00 -> 2026-08-03T01:42:23.259000+00:00 8.32
2026-08-03T01:42:47.071000+00:00 -> 2026-08-03T01:43:02.433000+00:00 15.362
2026-08-03T01:43:13.037000+00:00 -> 2026-08-03T01:43:25.591000+00:00 12.554
2026-08-03T01:44:10.575000+00:00 -> 2026-08-03T01:44:20.797000+00:00 10.222
2026-08-03T01:47:49.515000+00:00 -> 2026-08-03T01:48:00.736000+00:00 11.221
Average ThoughtBox duration per user/node:
swol       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=9.5060 s
swol       | Computer.computer1.choices_similarity    | count=1) | avg=20.9110 s
swol       | Computer.computer2.root                  | count=2) | avg=7.7000 s
swol       | Computer.computer.choices2_similarity    | count=1) | avg=6.1940 s
swol       | Scene2Break.part2.choice_similarity      | count=1) | avg=14.1160 s
swol       | Scene3Bedroom.main.choices_similarity    | count=1) | avg=9.6060 s
swol       | Scene4Backyard.mainConversation.choices_similarity | count=2) | avg=6.3270 s
swol       | Scene4Garage.phone1.root                 | count=1) | avg=18.7070 s
swol       | Scene4Garage.photo.choices_similarity    | count=1) | avg=12.6540 s
swol       | Scene4Bedroom.phone.root                 | count=1) | avg=18.8630 s
swol       | Scene6LunchRouteB.phone.root             | count=1) | avg=18.6420 s
tsvn       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=30.3760 s
tsvn       | Computer.computer1.choices_similarity    | count=1) | avg=24.4630 s
tsvn       | Computer.computer2.root                  | count=1) | avg=11.2200 s
tsvn       | Computer.computer.choices2_similarity    | count=1) | avg=20.6490 s
tsvn       | Scene2Break.part2.choice_similarity      | count=1) | avg=21.2430 s
tsvn       | Scene3Bedroom.main.choices_similarity    | count=3) | avg=12.5300 s
tsvn       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=15.0550 s
tsvn       | Scene4Garage.phone1.root                 | count=1) | avg=6.9030 s
tsvn       | Scene4Garage.photo.choices_similarity    | count=1) | avg=15.7500 s
tsvn       | Scene4Bedroom.phone.root                 | count=3) | avg=10.0053 s
tsvn       | Scene6BedroomRouteA1.phone.choices1_similarity | count=1) | avg=5.9760 s
mkps       | Scene1Classroom.part2.thanks_similarity  | count=2) | avg=16.7250 s
mkps       | Computer.computer1.choices_similarity    | count=2) | avg=20.3250 s
mkps       | Computer.computer2.root                  | count=1) | avg=18.6880 s
mkps       | Computer.computer.choices2_similarity    | count=1) | avg=13.7370 s
mkps       | Scene2Break.part2.choice_similarity      | count=2) | avg=16.8880 s
mkps       | Scene3Bedroom.main.choices_similarity    | count=2) | avg=8.0515 s
mkps       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=17.7960 s
mkps       | Scene4Garage.phone1.root                 | count=2) | avg=6.3100 s
mkps       | Scene4Garage.photo.choices_similarity    | count=1) | avg=11.2530 s
mkps       | Scene4Bedroom.phone.root                 | count=2) | avg=11.8160 s
mkps       | Scene6LunchRouteB.phone.root             | count=1) | avg=9.1960 s
eych       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=11.4380 s
eych       | Computer.computer1.choices_similarity    | count=1) | avg=14.5570 s
eych       | Computer.computer2.root                  | count=1) | avg=13.0580 s
eych       | Computer.computer.choices2_similarity    | count=1) | avg=12.9040 s
eych       | Scene2Break.part2.choice_similarity      | count=2) | avg=9.2040 s
eych       | Scene3Bedroom.main.choices_similarity    | count=2) | avg=10.6065 s
eych       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=11.5230 s
eych       | Scene4Garage.phone1.root                 | count=1) | avg=4.8550 s
eych       | Scene4Garage.photo.choices_similarity    | count=1) | avg=10.6280 s
eych       | Scene4Bedroom.phone.root                 | count=1) | avg=104.6430 s
eych       | Scene6BedroomRouteA1.phone.choices1_similarity | count=1) | avg=5.5240 s
flzl       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=47.9840 s
flzl       | Computer.computer1.choices_similarity    | count=1) | avg=60.0460 s
flzl       | Computer.computer2.root                  | count=1) | avg=35.7540 s
flzl       | Computer.computer.choices2_similarity    | count=3) | avg=19.4890 s
flzl       | Scene2Break.part2.choice_similarity      | count=1) | avg=11.0060 s
flzl       | Scene3Bedroom.main.choices_similarity    | count=3) | avg=20.9070 s
flzl       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=15.6840 s
flzl       | Scene4Garage.phone1.root                 | count=3) | avg=15.3330 s
flzl       | Scene4Garage.photo.choices_similarity    | count=1) | avg=15.2220 s
flzl       | Scene4Bedroom.phone.root                 | count=3) | avg=14.3170 s
flzl       | Scene6LunchRouteB.phone.root             | count=1) | avg=25.6010 s
krpb       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=12.0370 s
krpb       | Computer.computer1.choices_similarity    | count=1) | avg=14.9160 s
krpb       | Computer.computer2.root                  | count=1) | avg=22.4920 s
krpb       | Computer.computer.choices2_similarity    | count=1) | avg=7.5860 s
krpb       | Scene2Break.part2.choice_similarity      | count=2) | avg=19.0050 s
krpb       | Scene3Bedroom.main.choices_similarity    | count=2) | avg=8.5810 s
krpb       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=8.3200 s
krpb       | Scene4Garage.phone1.root                 | count=1) | avg=15.3620 s
krpb       | Scene4Garage.photo.choices_similarity    | count=1) | avg=12.5540 s
krpb       | Scene4Bedroom.phone.root                 | count=1) | avg=10.2220 s
krpb       | Scene6LunchRouteB.phone.root             | count=1) | avg=11.2210 s

In [30]:
with open(gameplay_path, "w", encoding="utf-8") as f:
	for record in records:
		f.write(json.dumps(record, ensure_ascii=False))
		f.write("\n")