In [88]:
import sys
sys.path.append('..')

from collections import defaultdict
from adaptation.misc import NameAnonymizer
from datetime import datetime
import pandas as pd
import json
import os

In [89]:
data_dir = "./data"
raw_dir = os.path.join(data_dir, "raw")
pretest_dir = os.path.join(raw_dir, "pretest")
postest_dir = os.path.join(raw_dir, "postest")
gameplay_raw_path = os.path.join(raw_dir, "gameplay", "full_xapi_data_33.ndjson")

processed_dir = os.path.join(data_dir, "processed")
pretest_path = os.path.join(processed_dir, "pretest.csv")
postest_path = os.path.join(processed_dir, "postest.csv")
gameplay_path = os.path.join(processed_dir, "gameplay.ndjson")

adaptation_dir = os.path.join("../adaptation", "data")
metadata_path = os.path.join(adaptation_dir, "metadata.json")
situation_dir = os.path.join(adaptation_dir, "processed")
whitelist_path = os.path.join(adaptation_dir, "name_whitelist.txt")
names_path = os.path.join(adaptation_dir, "nombres-propios-es.txt")

In [90]:
with open(metadata_path, "r", encoding="utf-8") as f:
	config = json.load(f)

node_order = []
node_context = {}

for key in sorted(config.keys(), key=int):
	item = config[key]

	scene = os.path.splitext(os.path.basename(item["file"]))[0]
	scene = scene[0].upper() + scene[1:]

	part = item["object"].split(".")[0]

	node = f"{scene}.{part}"

	node_order.append(node)

print(node_order)

['Scene1Classroom.part2', 'Scene1Bedroom1.computer1', 'Scene1Bedroom1.computer2', 'Scene1Bedroom2.computer', 'Scene2Break.part2', 'Scene3Bedroom.main', 'Scene4Backyard.mainConversation', 'Scene4Garage.phone1', 'Scene4Garage.photo', 'Scene4Bedroom.phone', 'Scene6BedroomRouteA1.phone', 'Scene6LunchRouteB.phone']

In [91]:
pretest_df = pd.read_csv(pretest_path, encoding="utf-8")
postest_df = pd.read_csv(postest_path, encoding="utf-8")

In [92]:
def extract_likert(value: str):
	return int(value.split(" - ")[0])

In [93]:
def load_json_files(dir: str) -> list[dict]:
	data = []

	for filename in os.listdir(dir):
		if filename.endswith(".json"):
			filepath = os.path.join(dir, filename)

			with open(filepath, "r", encoding="utf-8") as f:
				data.append(json.load(f))

	return data

In [94]:
pretests = load_json_files(pretest_dir)

In [95]:
rows = []

for pretest in pretests:
	# Las cuatro últimas respuestas corresponden a las preguntas likert
	values = list(pretest.values())
	likert_values = values[-4:]

	row = {
		"access_code": pretest["Código de acceso"],
		"age": int(pretest["Edad"]),
		"gender": pretest["Género"] or pretest["Género [Otro]"],
		"education_level": pretest["Nivel de estudios actual"],
		"study_area": pretest["Área principal de estudios"] or pretest["Área principal de estudios [Otro]"],
		"dialogue_advance_only": extract_likert(likert_values[0]),
		"dialogue_predefined_options": extract_likert(likert_values[1]),
		"dialogue_free_text": extract_likert(likert_values[2]),
		"dialogue_hybrid": extract_likert(likert_values[3]),
	}

	rows.append(row)

df = pd.DataFrame(rows)

In [96]:
print(df.dtypes)

access_code                      str
age                            int64
gender                           str
education_level                  str
study_area                       str
dialogue_advance_only          int64
dialogue_predefined_options    int64
dialogue_free_text             int64
dialogue_hybrid                int64
dtype: object

In [97]:
display(df)

,access_code,age,gender,education_level,study_area,dialogue_advance_only,dialogue_predefined_options,dialogue_free_text,dialogue_hybrid
0,22_gmvf,22,Masculino,Estudios universitarios,Ciencias de la Salud,2,4,3,4
1,22_tstp,22,Femenino,Estudios universitarios,Ciencias de la Salud,2,4,5,4
2,22_vezs,24,Femenino,Estudios universitarios,Ciencias Sociales,3,3,3,3
3,22_wuak,65,Femenino,Estudios universitarios,Educación,5,1,1,1

In [98]:
df.to_csv(pretest_path, index=False, encoding="utf-8")

In [99]:
postests = load_json_files(postest_dir)

In [100]:
rows = []

for postest in postests:
	values = list(postest.values())
	
	# Saltarse metadata
	# response_id, submission_date, last_page, language, seed,
	# access_code, start_date, last_action_date
	likert_values = values[8:-2]

	# Dividir en secciones
	sus = likert_values[:10]
	free_text = likert_values[10:13]
	hybrid = likert_values[13:17]
	preferences = likert_values[17:21]

	row = {
		"access_code": postest["Código de acceso"],

		# SUS
		"sus_use_frequently": extract_likert(sus[0]),
		"sus_unnecessarily_complex": extract_likert(sus[1]),
		"sus_easy_to_use": extract_likert(sus[2]),
		"sus_need_technical_support": extract_likert(sus[3]),
		"sus_well_integrated": extract_likert(sus[4]),
		"sus_too_much_inconsistency": extract_likert(sus[5]),
		"sus_easy_to_learn": extract_likert(sus[6]),
		"sus_cumbersome": extract_likert(sus[7]),
		"sus_confident": extract_likert(sus[8]),
		"sus_need_to_learn": extract_likert(sus[9]),

		# Texto libre
		"free_text_easy_to_express": extract_likert(free_text[0]),
		"free_text_understood": extract_likert(free_text[1]),
		"free_text_coherent_responses": extract_likert(free_text[2]),

		# Diálogos híbridos
		"hybrid_more_natural": extract_likert(hybrid[0]),
		"hybrid_more_freedom": extract_likert(hybrid[1]),
		"hybrid_improves_interaction": extract_likert(hybrid[2]),
		"hybrid_overall_satisfaction": extract_likert(hybrid[3]),

		# Preferencia de diálogos
		"dialogue_advance_only": extract_likert(preferences[0]),
		"dialogue_predefined_options": extract_likert(preferences[1]),
		"dialogue_free_text": extract_likert(preferences[2]),
		"dialogue_hybrid": extract_likert(preferences[3]),

		# Preguntas abiertas
		"liked_most": values[-2],
		"comments": values[-1],
	}

	rows.append(row)

df = pd.DataFrame(rows)

In [101]:
print(df.dtypes)

access_code                       str
sus_use_frequently              int64
sus_unnecessarily_complex       int64
sus_easy_to_use                 int64
sus_need_technical_support      int64
sus_well_integrated             int64
sus_too_much_inconsistency      int64
sus_easy_to_learn               int64
sus_cumbersome                  int64
sus_confident                   int64
sus_need_to_learn               int64
free_text_easy_to_express       int64
free_text_understood            int64
free_text_coherent_responses    int64
hybrid_more_natural             int64
hybrid_more_freedom             int64
hybrid_improves_interaction     int64
hybrid_overall_satisfaction     int64
dialogue_advance_only           int64
dialogue_predefined_options     int64
dialogue_free_text              int64
dialogue_hybrid                 int64
liked_most                        str
comments                          str
dtype: object

In [102]:
display(df)

,access_code,sus_use_frequently,sus_unnecessarily_complex,sus_easy_to_use,sus_need_technical_support,sus_well_integrated,sus_too_much_inconsistency,sus_easy_to_learn,sus_cumbersome,sus_confident,...,hybrid_more_natural,hybrid_more_freedom,hybrid_improves_interaction,hybrid_overall_satisfaction,dialogue_advance_only,dialogue_predefined_options,dialogue_free_text,dialogue_hybrid,liked_most,comments
0,22_gmvf,3,1,4,2,4,1,4,1,5,...,4,1,4,4,4,4,2,3,La habilidad de la IA generativa para desarrol...,"Deberían ser más permisivas las respuestas, ya..."
1,22_tstp,4,5,4,3,3,1,4,5,4,...,4,3,4,5,2,4,4,5,,Algunas partes exigia que respondieses una cos...
2,22_vezs,5,1,3,1,4,1,4,1,3,...,3,4,4,4,3,3,3,3,que sea automatizado,siento que esta bien equilibrado
3,22_wuak,4,3,4,2,4,2,5,2,4,...,4,4,5,5,5,4,3,3,,

In [103]:
df.to_csv(postest_path, index=False, encoding="utf-8")

In [104]:
with open(gameplay_raw_path, "r", encoding="utf-8") as f:
	records = [json.loads(line) for line in f]

print(f"Original records: {len(records)}")

Original records: 4925

In [105]:
# USUARIOS
users = {"vezs", "tstp", "wuak", "gmvf"}

records = [
	record for record in records
	if record["actor"]["account"]["name"] in users
]

print(f"Filtered records: {len(records)}")

Filtered records: 3839

In [106]:
THOUGHTBOX_EVENT_IDS = {
	"https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxStart",
	"https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxEnd",
}

DIALOG_TREE_PREFIX = "https://w3id.org/xapi/seriousgames/activity-types/dialog-tree/"

MATCHING_TEXT_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/MatchingText"
METHOD_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Method"

LSTM_USERS = {"vezs", "tstp"}
# LSTM_USERS = {}

filtered_records = []

for record in records:
	object_id = record.get("object", {}).get("id", "")

	if object_id in THOUGHTBOX_EVENT_IDS:
		filtered_records.append(record)
		continue

	if object_id.startswith(DIALOG_TREE_PREFIX):
		extensions = record.get("result", {}).get("extensions", {})

		if MATCHING_TEXT_EXTENSION in extensions:
			user = record.get("actor", {}).get("account", {}).get("name")

			if user in LSTM_USERS:
				extensions[METHOD_EXTENSION] = "lstm"
			
			filtered_records.append(record)

records = filtered_records

print(f"Records after event filtering: {len(records)}")

Records after event filtering: 240

In [107]:
records.sort(key=lambda record: record["timestamp"])

print(f"Records after event filtering: {len(records)}")

Records after event filtering: 240

In [108]:
print(node_order)

['Scene1Classroom.part2', 'Scene1Bedroom1.computer1', 'Scene1Bedroom1.computer2', 'Scene1Bedroom2.computer', 'Scene2Break.part2', 'Scene3Bedroom.main', 'Scene4Backyard.mainConversation', 'Scene4Garage.phone1', 'Scene4Garage.photo', 'Scene4Bedroom.phone', 'Scene6BedroomRouteA1.phone', 'Scene6LunchRouteB.phone']

In [109]:
situation_files = []

for file in os.listdir(situation_dir):
	if file.startswith("situation_") and file.endswith(".csv"):
		situation_files.append(file)

situation_files.sort(
	key=lambda file: int(file.replace("situation_", "").replace(".csv", ""))
)

situation_dfs = {}

for file in situation_files:
	situation_number = int(file.replace("situation_", "").replace(".csv", ""))
	situation_dfs[situation_number] = pd.read_csv(os.path.join(situation_dir, file))

print(len(situation_dfs))

12

In [110]:
name_anonymizer = NameAnonymizer(
	names_path=names_path,
	whitelist_path=whitelist_path,
	replacement="{{name}}"
)

In [111]:
BRANCH_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Branch"

for record in records:
	object_id = record.get("object", {}).get("id", "")

	if object_id.startswith(DIALOG_TREE_PREFIX):
		extensions = record.get("result", {}).get("extensions", {})

		# Solo procesar si el nodo no tiene Branch
		if BRANCH_EXTENSION not in extensions:
			# Quitar el prefijo del dialog tree
			node_name = object_id[len(DIALOG_TREE_PREFIX):]

			matching_text = extensions.get(MATCHING_TEXT_EXTENSION)

			# Quedarse con las dos primeras partes separadas por "."
			node_prefix = ".".join(node_name.split(".")[:2])
			node_prefix_parts = node_prefix.split(".")

			situation_number = None
			fallback_situation = None

			# print(node_order)
			for i, expected in enumerate(node_order, start=1):
				if expected == node_prefix:
					situation_number = i
					break

				expected_parts = expected.split(".")

				if fallback_situation is None:
					expected_parts = expected.split(".")
					if expected_parts[1] == node_prefix_parts[1]:
						fallback_situation = i

			if situation_number is None:
				situation_number = fallback_situation

			situation_df = situation_dfs[situation_number]

			matching_text_clean = name_anonymizer.anonymize_names(matching_text)
			match = situation_df[situation_df["text_clean"] == matching_text_clean]

			if not match.empty:
				choice = match.iloc[0]["choice"]
			else:
				raise ValueError(f"No se encontró ninguna choice para '{matching_text_clean}' (situación {situation_number}, nodo {node_prefix})")

			extensions[BRANCH_EXTENSION] = choice

			print(node_prefix, situation_number, matching_text, choice)

Scene1Classroom.part2 1 Holaaa buenas, soy cris, acabo de llegar y estoy todavía un poco perdido, y tú? friendly
Scene1Classroom.part2 1 Hola shy
Computer.computer1 2 Hey, si soy cris, me gusta mucho jajajja msg4
Computer.computer2 3 Puff desde hace mucho tiempo 2yearsResponse
Computer.computer 4 Ay pobre, dormiste mal o algo? ask2
Computer.computer 4 Ay pobre, dormiste mal o algo? ask2
Computer.computer 4 Ahh, me alegra que estés mejor ask2
Scene2Break.part2 5 Acepto aunque no sé si podré unsure
Scene3Bedroom.main 6 Bastante, no sé le da mal jajaja. Y a ti?? liked2
Scene3Bedroom.main 6 Bro siempre pienso que no puede superarse y siempre hace algo mejor liked2
Scene3Bedroom.main 6 Me ha encantado ha sido bastante divertido liked2
Scene4Backyard.mainConversation 7 Bien :) good2
Scene4Garage.phone1 8 Le han encantado!! Le han regalado ... msg2
Scene4Garage.photo 9 No truth2
Scene4Garage.photo 9 No truth2
Scene4Bedroom.phone 10 Ya acabo la fiesta, que tal tu noche? msg3
Scene4Bedroom.phone 10 Hola msg3
Scene6LunchRouteB.phone 12 Hola Lucía, qué tal estás? No quiero que estés enfadada, y me preocupa la discusión del otro día... Podemos hablarlo? msg2
Scene6LunchRouteB.phone 12 Oyeee, tas enfadao? :( msg2
Scene6LunchRouteB.phone 12 Hola, Pablo, ¿sigues enfadada conmigo? msg2
Scene1Classroom.part2 1 ¡Hola! Yo me llamo ja friendly
Computer.computer1 2 Holaa, pues bien msg4
Computer.computer2 3 Ni me acuerdo, la tira de años 2yearsResponse
Computer.computer 4 Espero que te mejores pronto. Si necesitas ayuda con la tarea, me dices. ask2
Computer.computer 4 Que raro bueno ya estas bien xddd noAsk2
Computer.computer 4 Ha tenido que ser grave para que no vayas a clase, me alegra que ya estés mejor ya contarás que tal sigues! Y si necesitas cualquier cosa aqui estamos ask2
Scene2Break.part2 5 Acepto aunque no sé si podré unsure
Scene3Bedroom.main 6 Bro siempre pienso que no puede superarse y siempre hace algo mejor liked2
Scene3Bedroom.main 6 guapisimo liked2
Scene4Backyard.mainConversation 7 Muy bien! good2
Scene4Garage.phone1 8 Sii msg2
Scene4Garage.photo 9 No truth2
Scene4Bedroom.phone 10 Holaaa, que tall? msg3
Scene4Bedroom.phone 10 Hola msg3
Scene6BedroomRouteA1.phone 11 El que ? msg3

In [112]:
NODE_EXTENSION = "https://w3id.org/xapi/seriousgame/extensions/Node"

for record in records:
	event = record.get("object", {}).get("id", "")

	if event in THOUGHTBOX_EVENT_IDS:
		extensions = record.get("result", {}).get("extensions", {})

		user = record.get("actor", {}).get("account", {}).get("name", "unknown")
		timestamp = record.get("timestamp", "unknown")
		node = extensions.get(NODE_EXTENSION, "unknown")

		event_name = event.split("/")[-1]

		print(f"{timestamp} | {user} | {event_name} | {node}")

2026-07-23T22:29:10.882Z | vezs | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-23T22:29:10.884Z | vezs | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-23T22:29:10.891Z | vezs | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-23T22:29:10.893Z | vezs | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-23T22:31:47.465Z | vezs | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-23T22:31:47.467Z | vezs | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-23T22:31:47.507Z | vezs | ThoughtBoxStart | Computer.computer2.root
2026-07-23T22:31:47.508Z | vezs | ThoughtBoxEnd | Computer.computer2.root
2026-07-23T22:34:54.627Z | vezs | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-23T22:34:54.628Z | vezs | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-23T22:34:54.631Z | vezs | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-23T22:34:54.632Z | vezs | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-23T22:34:54.635Z | vezs | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-23T22:34:54.636Z | vezs | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-23T22:37:15.426Z | vezs | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-23T22:37:15.428Z | vezs | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-23T22:39:34.050Z | vezs | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-23T22:39:34.052Z | vezs | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-23T22:39:34.055Z | vezs | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-23T22:39:34.057Z | vezs | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-23T22:39:34.059Z | vezs | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-23T22:39:34.060Z | vezs | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-23T22:41:55.834Z | vezs | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-23T22:41:55.835Z | vezs | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-23T22:41:55.862Z | vezs | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-23T22:41:55.863Z | vezs | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-23T22:41:55.869Z | vezs | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-23T22:41:55.871Z | vezs | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-23T22:41:55.873Z | vezs | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-23T22:41:55.874Z | vezs | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-23T22:44:08.143Z | vezs | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-23T22:44:08.145Z | vezs | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-23T22:44:08.149Z | vezs | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-23T22:44:08.151Z | vezs | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-23T22:49:43.662Z | vezs | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-07-23T22:49:43.663Z | vezs | ThoughtBoxEnd | Scene6LunchRouteB.phone.root
2026-07-23T22:49:43.665Z | vezs | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-07-23T22:49:43.667Z | vezs | ThoughtBoxEnd | Scene6LunchRouteB.phone.root
2026-07-23T22:49:43.669Z | vezs | ThoughtBoxStart | Scene6LunchRouteB.phone.root
2026-07-23T22:49:43.672Z | vezs | ThoughtBoxEnd | Scene6LunchRouteB.phone.root
2026-07-24T01:58:19.407Z | tstp | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-24T01:58:19.410Z | tstp | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-24T02:01:19.102Z | tstp | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-24T02:01:19.104Z | tstp | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-24T02:04:19.429Z | tstp | ThoughtBoxStart | Computer.computer2.root
2026-07-24T02:04:19.430Z | tstp | ThoughtBoxEnd | Computer.computer2.root
2026-07-24T02:06:46.137Z | tstp | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-24T02:06:46.139Z | tstp | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-24T02:06:46.141Z | tstp | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-24T02:06:46.143Z | tstp | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-24T02:06:46.145Z | tstp | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-24T02:06:46.149Z | tstp | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-24T02:09:46.343Z | tstp | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-24T02:09:46.345Z | tstp | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-24T02:14:46.026Z | tstp | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-24T02:14:46.028Z | tstp | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-24T02:14:46.030Z | tstp | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-24T02:14:46.032Z | tstp | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-24T02:17:45.858Z | tstp | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-24T02:17:45.862Z | tstp | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-24T02:17:45.901Z | tstp | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-24T02:20:45.982Z | tstp | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-24T02:20:45.994Z | tstp | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-24T02:20:45.995Z | tstp | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-24T02:22:11.075Z | tstp | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-24T02:22:11.077Z | tstp | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-24T02:22:11.080Z | tstp | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-24T02:22:11.082Z | tstp | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-24T02:28:14.550Z | tstp | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-24T02:28:14.552Z | tstp | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T21:00:05.098Z | wuak | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-28T21:00:05.099Z | wuak | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-28T21:06:05.155Z | wuak | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-28T21:09:04.795Z | wuak | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-28T21:09:04.798Z | wuak | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-28T21:09:04.803Z | wuak | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-28T21:09:04.805Z | wuak | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-28T21:12:05.036Z | wuak | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-28T21:18:05.106Z | wuak | ThoughtBoxStart | Computer.computer2.root
2026-07-28T21:18:05.108Z | wuak | ThoughtBoxEnd | Computer.computer2.root
2026-07-28T21:24:05.406Z | wuak | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-28T21:24:05.409Z | wuak | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-28T21:27:04.734Z | wuak | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-28T21:27:04.735Z | wuak | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-28T21:27:04.740Z | wuak | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-28T21:27:04.741Z | wuak | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-28T21:30:28.098Z | wuak | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-28T21:30:28.099Z | wuak | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-28T21:30:28.101Z | wuak | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-28T21:30:28.102Z | wuak | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-28T21:30:28.104Z | wuak | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-28T21:30:28.106Z | wuak | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-28T21:37:13.188Z | wuak | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-28T21:37:13.191Z | wuak | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-28T21:37:13.193Z | wuak | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-28T21:37:13.194Z | wuak | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-28T21:37:13.196Z | wuak | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-28T21:37:13.197Z | wuak | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-28T21:40:12.785Z | wuak | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T21:40:12.787Z | wuak | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T21:40:12.788Z | wuak | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T21:40:12.790Z | wuak | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T21:40:12.791Z | wuak | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T21:40:12.792Z | wuak | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T21:43:13.089Z | wuak | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-28T21:43:13.095Z | wuak | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-28T21:43:13.100Z | wuak | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-28T21:46:12.806Z | wuak | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-28T21:46:12.848Z | wuak | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-28T21:46:12.849Z | wuak | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-28T21:46:12.851Z | wuak | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-28T21:46:12.852Z | wuak | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-28T21:46:12.854Z | wuak | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-28T21:46:12.856Z | wuak | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-28T21:54:07.639Z | wuak | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T21:54:07.640Z | wuak | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T21:54:07.644Z | wuak | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T21:54:07.647Z | wuak | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T22:18:22.098Z | gmvf | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-28T22:18:22.101Z | gmvf | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-28T22:18:22.103Z | gmvf | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-28T22:18:22.105Z | gmvf | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-28T22:20:17.072Z | gmvf | ThoughtBoxStart | Scene1Classroom.part2.thanks_similarity
2026-07-28T22:20:17.074Z | gmvf | ThoughtBoxEnd | Scene1Classroom.part2.thanks_similarity
2026-07-28T22:22:59.731Z | gmvf | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-28T22:22:59.733Z | gmvf | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-28T22:22:59.735Z | gmvf | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-28T22:22:59.736Z | gmvf | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-28T22:22:59.739Z | gmvf | ThoughtBoxStart | Computer.computer1.choices_similarity
2026-07-28T22:22:59.740Z | gmvf | ThoughtBoxEnd | Computer.computer1.choices_similarity
2026-07-28T22:22:59.801Z | gmvf | ThoughtBoxStart | Computer.computer2.root
2026-07-28T22:22:59.802Z | gmvf | ThoughtBoxEnd | Computer.computer2.root
2026-07-28T22:24:13.468Z | gmvf | ThoughtBoxStart | Computer.computer.choices2_similarity
2026-07-28T22:24:13.469Z | gmvf | ThoughtBoxEnd | Computer.computer.choices2_similarity
2026-07-28T22:25:32.692Z | gmvf | ThoughtBoxStart | Scene2Break.part2.choice_similarity
2026-07-28T22:25:32.693Z | gmvf | ThoughtBoxEnd | Scene2Break.part2.choice_similarity
2026-07-28T22:27:14.892Z | gmvf | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-28T22:27:14.896Z | gmvf | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-28T22:27:14.899Z | gmvf | ThoughtBoxStart | Scene3Bedroom.main.choices_similarity
2026-07-28T22:27:14.900Z | gmvf | ThoughtBoxEnd | Scene3Bedroom.main.choices_similarity
2026-07-28T22:29:11.157Z | gmvf | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T22:29:11.159Z | gmvf | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T22:29:11.161Z | gmvf | ThoughtBoxStart | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T22:29:11.162Z | gmvf | ThoughtBoxEnd | Scene4Backyard.mainConversation.choices_similarity
2026-07-28T22:29:11.186Z | gmvf | ThoughtBoxStart | Scene4Garage.phone1.root
2026-07-28T22:29:11.187Z | gmvf | ThoughtBoxEnd | Scene4Garage.phone1.root
2026-07-28T22:31:08.839Z | gmvf | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-28T22:31:08.841Z | gmvf | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-28T22:31:08.843Z | gmvf | ThoughtBoxStart | Scene4Garage.photo.choices_similarity
2026-07-28T22:31:08.845Z | gmvf | ThoughtBoxEnd | Scene4Garage.photo.choices_similarity
2026-07-28T22:31:08.882Z | gmvf | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-28T22:31:08.884Z | gmvf | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-28T22:31:08.887Z | gmvf | ThoughtBoxStart | Scene4Bedroom.phone.root
2026-07-28T22:31:08.888Z | gmvf | ThoughtBoxEnd | Scene4Bedroom.phone.root
2026-07-28T22:35:05.807Z | gmvf | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T22:35:05.808Z | gmvf | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T22:35:05.810Z | gmvf | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T22:35:05.812Z | gmvf | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T22:35:05.815Z | gmvf | ThoughtBoxStart | Scene6BedroomRouteA1.phone.choices1_similarity
2026-07-28T22:35:05.817Z | gmvf | ThoughtBoxEnd | Scene6BedroomRouteA1.phone.choices1_similarity

In [113]:
for record in records:
	event = record.get("object", {}).get("id", "")

	if event.startswith(DIALOG_TREE_PREFIX):
		extensions = record.get("result", {}).get("extensions", {})
		
		user = record.get("actor", {}).get("account", {}).get("name", "unknown")
		timestamp = record.get("timestamp", "unknown")
		matching_text = extensions.get(MATCHING_TEXT_EXTENSION, "unknown")

		event_name = event.split("/")[-1]

		print(f"{timestamp} | {user} | {event_name} | {matching_text}")

2026-07-23T22:29:10.883Z | vezs | Scene1Classroom.part2.thanks_similarity | Holaaa buenas, soy cris, acabo de llegar y estoy todavía un poco perdido, y tú?
2026-07-23T22:29:10.892Z | vezs | Scene1Classroom.part2.thanks_similarity | Hola
2026-07-23T22:31:47.466Z | vezs | Computer.computer1.choices_similarity | Hey, si soy cris, me gusta mucho jajajja
2026-07-23T22:31:47.508Z | vezs | Computer.computer2.root | Puff desde hace mucho tiempo
2026-07-23T22:34:54.627Z | vezs | Computer.computer.choices2_similarity | Ay pobre, dormiste mal o algo?
2026-07-23T22:34:54.631Z | vezs | Computer.computer.choices2_similarity | Ay pobre, dormiste mal o algo?
2026-07-23T22:34:54.636Z | vezs | Computer.computer.choices2_similarity | Ahh, me alegra que estés mejor
2026-07-23T22:37:15.427Z | vezs | Scene2Break.part2.choice_similarity | Acepto aunque no sé si podré
2026-07-23T22:39:34.051Z | vezs | Scene3Bedroom.main.choices_similarity | Bastante, no sé le da mal jajaja. Y a ti??
2026-07-23T22:39:34.056Z | vezs | Scene3Bedroom.main.choices_similarity | Bro siempre pienso que no puede superarse y siempre hace algo mejor
2026-07-23T22:39:34.059Z | vezs | Scene3Bedroom.main.choices_similarity | Me ha encantado ha sido bastante divertido
2026-07-23T22:41:55.834Z | vezs | Scene4Backyard.mainConversation.choices_similarity | Bien :)
2026-07-23T22:41:55.863Z | vezs | Scene4Garage.phone1.root | Le han encantado!! Le han regalado ...
2026-07-23T22:41:55.870Z | vezs | Scene4Garage.photo.choices_similarity | No
2026-07-23T22:41:55.874Z | vezs | Scene4Garage.photo.choices_similarity | No
2026-07-23T22:44:08.144Z | vezs | Scene4Bedroom.phone.root | Ya acabo la fiesta, que tal tu noche?
2026-07-23T22:44:08.150Z | vezs | Scene4Bedroom.phone.root | Hola
2026-07-23T22:49:43.663Z | vezs | Scene6LunchRouteB.phone.root | Hola Lucía, qué tal estás? No quiero que estés enfadada, y me preocupa la discusión del otro día... Podemos hablarlo?
2026-07-23T22:49:43.667Z | vezs | Scene6LunchRouteB.phone.root | Oyeee, tas enfadao? :(
2026-07-23T22:49:43.670Z | vezs | Scene6LunchRouteB.phone.root | Hola, Pablo, ¿sigues enfadada conmigo?
2026-07-24T01:58:19.409Z | tstp | Scene1Classroom.part2.thanks_similarity | ¡Hola! Yo me llamo ja
2026-07-24T02:01:19.103Z | tstp | Computer.computer1.choices_similarity | Holaa, pues bien
2026-07-24T02:04:19.430Z | tstp | Computer.computer2.root | Ni me acuerdo, la tira de años
2026-07-24T02:06:46.139Z | tstp | Computer.computer.choices2_similarity | Espero que te mejores pronto. Si necesitas ayuda con la tarea, me dices.
2026-07-24T02:06:46.143Z | tstp | Computer.computer.choices2_similarity | Que raro bueno ya estas bien xddd
2026-07-24T02:06:46.148Z | tstp | Computer.computer.choices2_similarity | Ha tenido que ser grave para que no vayas a clase, me alegra que ya estés mejor ya contarás que tal sigues! Y si necesitas cualquier cosa aqui estamos
2026-07-24T02:09:46.344Z | tstp | Scene2Break.part2.choice_similarity | Acepto aunque no sé si podré
2026-07-24T02:14:46.027Z | tstp | Scene3Bedroom.main.choices_similarity | Bro siempre pienso que no puede superarse y siempre hace algo mejor
2026-07-24T02:14:46.032Z | tstp | Scene3Bedroom.main.choices_similarity | guapisimo
2026-07-24T02:17:45.859Z | tstp | Scene4Backyard.mainConversation.choices_similarity | Muy bien!
2026-07-24T02:20:45.980Z | tstp | Scene4Garage.phone1.root | Sii
2026-07-24T02:20:45.995Z | tstp | Scene4Garage.photo.choices_similarity | No
2026-07-24T02:22:11.076Z | tstp | Scene4Bedroom.phone.root | Holaaa, que tall?
2026-07-24T02:22:11.081Z | tstp | Scene4Bedroom.phone.root | Hola
2026-07-24T02:28:14.551Z | tstp | Scene6BedroomRouteA1.phone.choices1_similarity | El que ?
2026-07-28T21:00:05.098Z | wuak | Scene1Classroom.part2.thanks_similarity | Hola
2026-07-28T21:09:04.794Z | wuak | Computer.computer1.choices_similarity | A si? Jajajs, es un grande ToniVlogs
2026-07-28T21:09:04.799Z | wuak | Computer.computer1.choices_similarity | Holaaaaa, sí me encanta ToniVlogs
2026-07-28T21:12:05.035Z | wuak | Computer.computer1.choices_similarity | ¡Hola! Siiiii, ¡me encantan sus vídeos!
2026-07-28T21:18:05.107Z | wuak | Computer.computer2.root | Desde hace 2 años.
2026-07-28T21:24:05.408Z | wuak | Computer.computer.choices2_similarity | Menos mal, espero que te recuperes pronto.
2026-07-28T21:27:04.734Z | wuak | Computer.computer.choices2_similarity | Ay no pobre cómo estás ahora ?
2026-07-28T21:27:04.741Z | wuak | Computer.computer.choices2_similarity | Ay no pobre cómo estás ahora ?
2026-07-28T21:30:28.099Z | wuak | Scene2Break.part2.choice_similarity | Pues claro, ¿dónde hay que firmar?
2026-07-28T21:30:28.101Z | wuak | Scene2Break.part2.choice_similarity | Pues claro, ¿dónde hay que firmar?
2026-07-28T21:30:28.106Z | wuak | Scene2Break.part2.choice_similarity | De acuerdo. alli estare
2026-07-28T21:37:13.189Z | wuak | Scene3Bedroom.main.choices_similarity | Me ha hecho la tarde, vaya risass
2026-07-28T21:37:13.193Z | wuak | Scene3Bedroom.main.choices_similarity | Me ha hecho la tarde, vaya risass
2026-07-28T21:37:13.197Z | wuak | Scene3Bedroom.main.choices_similarity | Me ha hecho la tarde, vaya risass
2026-07-28T21:40:12.786Z | wuak | Scene4Backyard.mainConversation.choices_similarity | Hay bastante gente que todavía no conozco pero de momento bien.
2026-07-28T21:40:12.789Z | wuak | Scene4Backyard.mainConversation.choices_similarity | Guay la verdad q la gente es muy maja aqui
2026-07-28T21:40:12.792Z | wuak | Scene4Backyard.mainConversation.choices_similarity | Guay la verdad q la gente es muy maja aqui
2026-07-28T21:43:13.095Z | wuak | Scene4Garage.phone1.root | Si, parece que si
2026-07-28T21:46:12.804Z | wuak | Scene4Garage.photo.choices_similarity | No
2026-07-28T21:46:12.848Z | wuak | Scene4Bedroom.phone.root | Como estás?
2026-07-28T21:46:12.852Z | wuak | Scene4Bedroom.phone.root | Como estás?
2026-07-28T21:46:12.855Z | wuak | Scene4Bedroom.phone.root | Como estás?
2026-07-28T21:54:07.640Z | wuak | Scene6BedroomRouteA1.phone.choices1_similarity | Vale, cuéntame
2026-07-28T21:54:07.646Z | wuak | Scene6BedroomRouteA1.phone.choices1_similarity | Sorpréndeme jajaj
2026-07-28T22:18:22.100Z | gmvf | Scene1Classroom.part2.thanks_similarity | Mucho gusto Laura! Soy férmin, ¿cómo estás?
2026-07-28T22:18:22.104Z | gmvf | Scene1Classroom.part2.thanks_similarity | H-hola.
2026-07-28T22:20:17.073Z | gmvf | Scene1Classroom.part2.thanks_similarity | Hola
2026-07-28T22:22:59.732Z | gmvf | Computer.computer1.choices_similarity | Ah djasdjashda guay
2026-07-28T22:22:59.735Z | gmvf | Computer.computer1.choices_similarity | En serio? Que guay. Llevo viendo a ese youtuber desde hace muchisimo tiempo.
2026-07-28T22:22:59.739Z | gmvf | Computer.computer1.choices_similarity | Ah djasdjashda guay
2026-07-28T22:22:59.801Z | gmvf | Computer.computer2.root | Prácticamente desde los inicios! Cuando le vi en un vídeo de otro youtuber al que sigo
2026-07-28T22:24:13.469Z | gmvf | Computer.computer.choices2_similarity | Ay pobre, dormiste mal o algo?
2026-07-28T22:25:32.692Z | gmvf | Scene2Break.part2.choice_similarity | Sii por supuesto, me apunto
2026-07-28T22:27:14.895Z | gmvf | Scene3Bedroom.main.choices_similarity | Me ha gustado muckk
2026-07-28T22:27:14.900Z | gmvf | Scene3Bedroom.main.choices_similarity | Me ha gustado muckk
2026-07-28T22:29:11.157Z | gmvf | Scene4Backyard.mainConversation.choices_similarity | Bieeen, en una fiesta de cumpleaños. ¿Que tal tú?
2026-07-28T22:29:11.161Z | gmvf | Scene4Backyard.mainConversation.choices_similarity | Bien :)
2026-07-28T22:29:11.186Z | gmvf | Scene4Garage.phone1.root | Si, parece que si
2026-07-28T22:31:08.840Z | gmvf | Scene4Garage.photo.choices_similarity | No, ¿te importa si le mando la foto?
2026-07-28T22:31:08.844Z | gmvf | Scene4Garage.photo.choices_similarity | No
2026-07-28T22:31:08.883Z | gmvf | Scene4Bedroom.phone.root | Holaaa, que tall?
2026-07-28T22:31:08.887Z | gmvf | Scene4Bedroom.phone.root | Hola
2026-07-28T22:35:05.808Z | gmvf | Scene6BedroomRouteA1.phone.choices1_similarity | depende jaja que idea tienes ?
2026-07-28T22:35:05.811Z | gmvf | Scene6BedroomRouteA1.phone.choices1_similarity | Hmm? Depende de lo que sea, cuéntame
2026-07-28T22:35:05.816Z | gmvf | Scene6BedroomRouteA1.phone.choices1_similarity | Dime

In [117]:
START_EVENT = "https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxStart"
END_EVENT = "https://w3id.org/xapi/lab/activity-types/story-node/ThoughtBoxEnd"

# Comienzos para cada (usuario, nodo)
pending_starts = defaultdict(list)

# Duraciones para cada (usuario, nodo)
durations = defaultdict(list)

matches = defaultdict(list)

for record in records:
	event = record.get("object", {}).get("id")
	user = record.get("actor", {}).get("account", {}).get("name")
	node = record.get("result", {}).get("extensions", {}).get(NODE_EXTENSION)

	timestamp = datetime.fromisoformat(record["timestamp"].replace("Z", "+00:00"))

	key = (user, node)

	if event == START_EVENT:
		pending_starts[key].append(timestamp)

	elif event == END_EVENT:
		if pending_starts[key]:
			start = pending_starts[key].pop(0)
			duration = (timestamp - start).total_seconds()

			durations[key].append(duration)
			matches[key].append((start, timestamp, duration))

for (user, node), pairs in matches.items():
    for start, end, duration in pairs[:5]:
        print(start.isoformat(), "->", end.isoformat(), duration)

print("Average ThoughtBox duration per user/node:")
for (user, node), values in durations.items():
	avg = sum(values) / len(values)
	print(f"{user:10} | {node:40} | count={len(values)}) | avg={avg:.4f} s")

anomalous_intervals = []

print("\nLong durations (>60 s):")
for (user, node), pairs in matches.items():
	for start, end, duration in pairs:
		if duration > 120:
			anomalous_intervals.append((user, node, start, end))

			print(
				f"User : {user}\n"
				f"Node : {node}\n"
				f"Start: {start.isoformat()}\n"
				f"End  : {end.isoformat()}\n"
				f"Δt   : {duration:.4f} s\n"
			)

2026-07-23T22:29:10.882000+00:00 -> 2026-07-23T22:29:10.884000+00:00 0.002
2026-07-23T22:29:10.891000+00:00 -> 2026-07-23T22:29:10.893000+00:00 0.002
2026-07-23T22:31:47.465000+00:00 -> 2026-07-23T22:31:47.467000+00:00 0.002
2026-07-23T22:31:47.507000+00:00 -> 2026-07-23T22:31:47.508000+00:00 0.001
2026-07-23T22:34:54.627000+00:00 -> 2026-07-23T22:34:54.628000+00:00 0.001
2026-07-23T22:34:54.631000+00:00 -> 2026-07-23T22:34:54.632000+00:00 0.001
2026-07-23T22:34:54.635000+00:00 -> 2026-07-23T22:34:54.636000+00:00 0.001
2026-07-23T22:37:15.426000+00:00 -> 2026-07-23T22:37:15.428000+00:00 0.002
2026-07-23T22:39:34.050000+00:00 -> 2026-07-23T22:39:34.052000+00:00 0.002
2026-07-23T22:39:34.055000+00:00 -> 2026-07-23T22:39:34.057000+00:00 0.002
2026-07-23T22:39:34.059000+00:00 -> 2026-07-23T22:39:34.060000+00:00 0.001
2026-07-23T22:41:55.834000+00:00 -> 2026-07-23T22:41:55.835000+00:00 0.001
2026-07-23T22:41:55.862000+00:00 -> 2026-07-23T22:41:55.863000+00:00 0.001
2026-07-23T22:41:55.869000+00:00 -> 2026-07-23T22:41:55.871000+00:00 0.002
2026-07-23T22:41:55.873000+00:00 -> 2026-07-23T22:41:55.874000+00:00 0.001
2026-07-23T22:44:08.143000+00:00 -> 2026-07-23T22:44:08.145000+00:00 0.002
2026-07-23T22:44:08.149000+00:00 -> 2026-07-23T22:44:08.151000+00:00 0.002
2026-07-23T22:49:43.662000+00:00 -> 2026-07-23T22:49:43.663000+00:00 0.001
2026-07-23T22:49:43.665000+00:00 -> 2026-07-23T22:49:43.667000+00:00 0.002
2026-07-23T22:49:43.669000+00:00 -> 2026-07-23T22:49:43.672000+00:00 0.003
2026-07-24T01:58:19.407000+00:00 -> 2026-07-24T01:58:19.410000+00:00 0.003
2026-07-24T02:01:19.102000+00:00 -> 2026-07-24T02:01:19.104000+00:00 0.002
2026-07-24T02:04:19.429000+00:00 -> 2026-07-24T02:04:19.430000+00:00 0.001
2026-07-24T02:06:46.137000+00:00 -> 2026-07-24T02:06:46.139000+00:00 0.002
2026-07-24T02:06:46.141000+00:00 -> 2026-07-24T02:06:46.143000+00:00 0.002
2026-07-24T02:06:46.145000+00:00 -> 2026-07-24T02:06:46.149000+00:00 0.004
2026-07-24T02:09:46.343000+00:00 -> 2026-07-24T02:09:46.345000+00:00 0.002
2026-07-24T02:14:46.026000+00:00 -> 2026-07-24T02:14:46.028000+00:00 0.002
2026-07-24T02:14:46.030000+00:00 -> 2026-07-24T02:14:46.032000+00:00 0.002
2026-07-24T02:17:45.858000+00:00 -> 2026-07-24T02:17:45.862000+00:00 0.004
2026-07-24T02:20:45.994000+00:00 -> 2026-07-24T02:20:45.995000+00:00 0.001
2026-07-24T02:22:11.075000+00:00 -> 2026-07-24T02:22:11.077000+00:00 0.002
2026-07-24T02:22:11.080000+00:00 -> 2026-07-24T02:22:11.082000+00:00 0.002
2026-07-24T02:28:14.550000+00:00 -> 2026-07-24T02:28:14.552000+00:00 0.002
2026-07-28T21:00:05.098000+00:00 -> 2026-07-28T21:00:05.099000+00:00 0.001
2026-07-28T21:09:04.798000+00:00 -> 2026-07-28T21:09:04.803000+00:00 0.005
2026-07-28T21:18:05.106000+00:00 -> 2026-07-28T21:18:05.108000+00:00 0.002
2026-07-28T21:24:05.406000+00:00 -> 2026-07-28T21:24:05.409000+00:00 0.003
2026-07-28T21:27:04.734000+00:00 -> 2026-07-28T21:27:04.735000+00:00 0.001
2026-07-28T21:27:04.740000+00:00 -> 2026-07-28T21:27:04.741000+00:00 0.001
2026-07-28T21:30:28.098000+00:00 -> 2026-07-28T21:30:28.099000+00:00 0.001
2026-07-28T21:30:28.101000+00:00 -> 2026-07-28T21:30:28.102000+00:00 0.001
2026-07-28T21:30:28.104000+00:00 -> 2026-07-28T21:30:28.106000+00:00 0.002
2026-07-28T21:37:13.188000+00:00 -> 2026-07-28T21:37:13.191000+00:00 0.003
2026-07-28T21:37:13.193000+00:00 -> 2026-07-28T21:37:13.194000+00:00 0.001
2026-07-28T21:37:13.196000+00:00 -> 2026-07-28T21:37:13.197000+00:00 0.001
2026-07-28T21:40:12.785000+00:00 -> 2026-07-28T21:40:12.787000+00:00 0.002
2026-07-28T21:40:12.788000+00:00 -> 2026-07-28T21:40:12.790000+00:00 0.002
2026-07-28T21:40:12.791000+00:00 -> 2026-07-28T21:40:12.792000+00:00 0.001
2026-07-28T21:43:13.089000+00:00 -> 2026-07-28T21:43:13.095000+00:00 0.006
2026-07-28T21:46:12.848000+00:00 -> 2026-07-28T21:46:12.849000+00:00 0.001
2026-07-28T21:46:12.851000+00:00 -> 2026-07-28T21:46:12.852000+00:00 0.001
2026-07-28T21:46:12.854000+00:00 -> 2026-07-28T21:46:12.856000+00:00 0.002
2026-07-28T21:54:07.639000+00:00 -> 2026-07-28T21:54:07.640000+00:00 0.001
2026-07-28T21:54:07.644000+00:00 -> 2026-07-28T21:54:07.647000+00:00 0.003
2026-07-28T22:18:22.098000+00:00 -> 2026-07-28T22:18:22.101000+00:00 0.003
2026-07-28T22:18:22.103000+00:00 -> 2026-07-28T22:18:22.105000+00:00 0.002
2026-07-28T22:20:17.072000+00:00 -> 2026-07-28T22:20:17.074000+00:00 0.002
2026-07-28T22:22:59.731000+00:00 -> 2026-07-28T22:22:59.733000+00:00 0.002
2026-07-28T22:22:59.735000+00:00 -> 2026-07-28T22:22:59.736000+00:00 0.001
2026-07-28T22:22:59.739000+00:00 -> 2026-07-28T22:22:59.740000+00:00 0.001
2026-07-28T22:22:59.801000+00:00 -> 2026-07-28T22:22:59.802000+00:00 0.001
2026-07-28T22:24:13.468000+00:00 -> 2026-07-28T22:24:13.469000+00:00 0.001
2026-07-28T22:25:32.692000+00:00 -> 2026-07-28T22:25:32.693000+00:00 0.001
2026-07-28T22:27:14.892000+00:00 -> 2026-07-28T22:27:14.896000+00:00 0.004
2026-07-28T22:27:14.899000+00:00 -> 2026-07-28T22:27:14.900000+00:00 0.001
2026-07-28T22:29:11.157000+00:00 -> 2026-07-28T22:29:11.159000+00:00 0.002
2026-07-28T22:29:11.161000+00:00 -> 2026-07-28T22:29:11.162000+00:00 0.001
2026-07-28T22:29:11.186000+00:00 -> 2026-07-28T22:29:11.187000+00:00 0.001
2026-07-28T22:31:08.839000+00:00 -> 2026-07-28T22:31:08.841000+00:00 0.002
2026-07-28T22:31:08.843000+00:00 -> 2026-07-28T22:31:08.845000+00:00 0.002
2026-07-28T22:31:08.882000+00:00 -> 2026-07-28T22:31:08.884000+00:00 0.002
2026-07-28T22:31:08.887000+00:00 -> 2026-07-28T22:31:08.888000+00:00 0.001
2026-07-28T22:35:05.807000+00:00 -> 2026-07-28T22:35:05.808000+00:00 0.001
2026-07-28T22:35:05.810000+00:00 -> 2026-07-28T22:35:05.812000+00:00 0.002
2026-07-28T22:35:05.815000+00:00 -> 2026-07-28T22:35:05.817000+00:00 0.002
Average ThoughtBox duration per user/node:
vezs       | Scene1Classroom.part2.thanks_similarity  | count=2) | avg=0.0020 s
vezs       | Computer.computer1.choices_similarity    | count=1) | avg=0.0020 s
vezs       | Computer.computer2.root                  | count=1) | avg=0.0010 s
vezs       | Computer.computer.choices2_similarity    | count=3) | avg=0.0010 s
vezs       | Scene2Break.part2.choice_similarity      | count=1) | avg=0.0020 s
vezs       | Scene3Bedroom.main.choices_similarity    | count=3) | avg=0.0017 s
vezs       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=0.0010 s
vezs       | Scene4Garage.phone1.root                 | count=1) | avg=0.0010 s
vezs       | Scene4Garage.photo.choices_similarity    | count=2) | avg=0.0015 s
vezs       | Scene4Bedroom.phone.root                 | count=2) | avg=0.0020 s
vezs       | Scene6LunchRouteB.phone.root             | count=3) | avg=0.0020 s
tstp       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=0.0030 s
tstp       | Computer.computer1.choices_similarity    | count=1) | avg=0.0020 s
tstp       | Computer.computer2.root                  | count=1) | avg=0.0010 s
tstp       | Computer.computer.choices2_similarity    | count=3) | avg=0.0027 s
tstp       | Scene2Break.part2.choice_similarity      | count=1) | avg=0.0020 s
tstp       | Scene3Bedroom.main.choices_similarity    | count=2) | avg=0.0020 s
tstp       | Scene4Backyard.mainConversation.choices_similarity | count=1) | avg=0.0040 s
tstp       | Scene4Garage.photo.choices_similarity    | count=1) | avg=0.0010 s
tstp       | Scene4Bedroom.phone.root                 | count=2) | avg=0.0020 s
tstp       | Scene6BedroomRouteA1.phone.choices1_similarity | count=1) | avg=0.0020 s
wuak       | Scene1Classroom.part2.thanks_similarity  | count=1) | avg=0.0010 s
wuak       | Computer.computer1.choices_similarity    | count=1) | avg=0.0050 s
wuak       | Computer.computer2.root                  | count=1) | avg=0.0020 s
wuak       | Computer.computer.choices2_similarity    | count=3) | avg=0.0017 s
wuak       | Scene2Break.part2.choice_similarity      | count=3) | avg=0.0013 s
wuak       | Scene3Bedroom.main.choices_similarity    | count=3) | avg=0.0017 s
wuak       | Scene4Backyard.mainConversation.choices_similarity | count=3) | avg=0.0017 s
wuak       | Scene4Garage.phone1.root                 | count=1) | avg=0.0060 s
wuak       | Scene4Bedroom.phone.root                 | count=3) | avg=0.0013 s
wuak       | Scene6BedroomRouteA1.phone.choices1_similarity | count=2) | avg=0.0020 s
gmvf       | Scene1Classroom.part2.thanks_similarity  | count=3) | avg=0.0023 s
gmvf       | Computer.computer1.choices_similarity    | count=3) | avg=0.0013 s
gmvf       | Computer.computer2.root                  | count=1) | avg=0.0010 s
gmvf       | Computer.computer.choices2_similarity    | count=1) | avg=0.0010 s
gmvf       | Scene2Break.part2.choice_similarity      | count=1) | avg=0.0010 s
gmvf       | Scene3Bedroom.main.choices_similarity    | count=2) | avg=0.0025 s
gmvf       | Scene4Backyard.mainConversation.choices_similarity | count=2) | avg=0.0015 s
gmvf       | Scene4Garage.phone1.root                 | count=1) | avg=0.0010 s
gmvf       | Scene4Garage.photo.choices_similarity    | count=2) | avg=0.0020 s
gmvf       | Scene4Bedroom.phone.root                 | count=2) | avg=0.0015 s
gmvf       | Scene6BedroomRouteA1.phone.choices1_similarity | count=3) | avg=0.0017 s

Long durations (>60 s):

In [115]:
filtered_records = []

for record in records:
	user = record.get("actor", {}).get("account", {}).get("name")
	node = record.get("result", {}).get("extensions", {}).get(NODE_EXTENSION)

	timestamp = datetime.fromisoformat(record["timestamp"].replace("Z", "+00:00"))

	remove = False

	for bad_user, bad_node, start, end in anomalous_intervals:
		if user == bad_user and node == bad_node and start <= timestamp <= end:
			remove = True
			break

	if not remove:
		filtered_records.append(record)

removed_count = len(records) - len(filtered_records)

records = filtered_records

print(f"Removed records: {removed_count}")
print(f"Records after removing anomalous intervals: {len(records)}")

Removed records: 8
Records after removing anomalous intervals: 232

In [116]:
with open(gameplay_path, "w", encoding="utf-8") as f:
	for record in records:
		f.write(json.dumps(record, ensure_ascii=False))
		f.write("\n")